-- Jalankan di Supabase SQL Editor pada PROJECT KHUSUS INTERNAL.
-- Jangan jalankan ulang di basis data yang berisi data produksi tanpa backup.
-- Sesudah membuat akun di Authentication, tetapkan profil administrator menggunakan contoh di README.

create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 nama text not null,
 role text not null check (role in ('admin','editor','viewer')),
 created_at timestamptz not null default now()
);

create or replace function public.current_app_role() returns text
 language sql stable security definer set search_path = public
 as $$ select role from public.profiles where id = (select auth.uid()) limit 1 $$;
revoke all on function public.current_app_role() from public, anon;
grant execute on function public.current_app_role() to authenticated;

create table if not exists public.bottlenecks (
 no integer primary key,
 kategori text not null,
 risiko text,
 tindak_lanjut text,
 jalur text,
 pic text,
 koordinasi text,
 prioritas text,
 deadline date,
 output text,
 status text not null default 'Belum Mulai',
 keputusan text,
 updated_at timestamptz not null default now()
);
create table if not exists public.action_plans (
 no integer primary key,
 fase text,
 kegiatan text not null,
 langkah text,
 pic text,
 mulai date,
 deadline date,
 output text,
 prioritas text,
 status text not null default 'Belum Mulai',
 progres integer not null default 0 check (progres between 0 and 100),
 updated_at timestamptz not null default now()
);
create table if not exists public.bank_recap (
 bank text primary key check (bank in ('Mandiri','BRI','BSI')),
 jumlah_sdm integer check (jumlah_sdm >= 0),
 kewajiban_total numeric(18,0) check (kewajiban_total >= 0),
 realisasi_netto numeric(18,0) check (realisasi_netto >= 0),
 gagal_terakhir integer check (gagal_terakhir >= 0),
 cutoff date,
 status text,
 bukti text,
 catatan text,
 updated_at timestamptz not null default now(),
 constraint bank_realization_not_over_obligation check (realisasi_netto is null or kewajiban_total is null or realisasi_netto <= kewajiban_total)
);
create table if not exists public.sdm_cases (
 id bigint generated by default as identity primary key,
 nip varchar(18) not null unique check (nip ~ '^[0-9]{18}$'),
 nama text not null,
 provinsi text,
 kab_kota text,
 bank text not null,
 kategori text,
 kewajiban_total numeric(18,0) not null default 0 check (kewajiban_total >= 0),
 realisasi_total numeric(18,0) not null default 0 check (realisasi_total >= 0 and realisasi_total <= kewajiban_total),
 sisa_kewajiban numeric(18,0) generated always as (kewajiban_total - realisasi_total) stored,
 tahap_terakhir text,
 jalur_penyelesaian text,
 pic text,
 deadline date,
 status text not null default 'Belum Ditindaklanjuti',
 bukti text,
 tanggal_pembayaran date,
 catatan text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 constraint verified_payment_must_have_evidence check (status <> 'Lunas Terverifikasi' or (kewajiban_total > 0 and realisasi_total = kewajiban_total and nullif(btrim(bukti),'') is not null and tanggal_pembayaran is not null))
);
create index if not exists idx_cases_province on public.sdm_cases(provinsi);
create index if not exists idx_cases_status on public.sdm_cases(status);
create index if not exists idx_cases_category on public.sdm_cases(kategori);
create index if not exists idx_cases_updated on public.sdm_cases(updated_at desc);
create index if not exists idx_cases_name on public.sdm_cases(nama);

create table if not exists public.audit_events (
 id bigint generated by default as identity primary key,
 actor uuid,
 entity text not null,
 row_key text not null,
 action text not null,
 old_data jsonb,
 new_data jsonb,
 occurred_at timestamptz not null default now()
);

create or replace function public.touch_updated_at() returns trigger
 language plpgsql set search_path = public as $$
 begin new.updated_at := now(); return new; end $$;
create or replace function public.record_audit_event() returns trigger
 language plpgsql security definer set search_path = public as $$
 begin
 insert into public.audit_events(actor,entity,row_key,action,old_data,new_data)
 values(auth.uid(),TG_TABLE_NAME,case when TG_OP='DELETE' then coalesce(to_jsonb(old)->>'nip',to_jsonb(old)->>'no',to_jsonb(old)->>'bank') else coalesce(to_jsonb(new)->>'nip',to_jsonb(new)->>'no',to_jsonb(new)->>'bank') end,TG_OP,
 case when TG_OP='INSERT' then null else to_jsonb(old) end,
 case when TG_OP='DELETE' then null else to_jsonb(new) end);
 return coalesce(new,old);
 end $$;
revoke all on function public.record_audit_event() from public,anon,authenticated;

DO $$ declare tbl text; begin
 foreach tbl in array array['bottlenecks','action_plans','bank_recap','sdm_cases'] loop
  execute format('drop trigger if exists touch_modified on public.%I',tbl);
  execute format('create trigger touch_modified before update on public.%I for each row execute function public.touch_updated_at()',tbl);
  execute format('drop trigger if exists audit_modified on public.%I',tbl);
  execute format('create trigger audit_modified after insert or update or delete on public.%I for each row execute function public.record_audit_event()',tbl);
 end loop;
end $$;

alter table public.profiles enable row level security;
alter table public.bottlenecks enable row level security;
alter table public.action_plans enable row level security;
alter table public.bank_recap enable row level security;
alter table public.sdm_cases enable row level security;
alter table public.audit_events enable row level security;

revoke all on public.profiles, public.bottlenecks, public.action_plans, public.bank_recap, public.sdm_cases, public.audit_events from anon;
revoke all on public.profiles, public.bottlenecks, public.action_plans, public.bank_recap, public.sdm_cases, public.audit_events from authenticated;
grant select on public.profiles, public.bottlenecks, public.action_plans, public.bank_recap, public.sdm_cases to authenticated;
grant insert, update on public.bottlenecks,public.action_plans,public.bank_recap,public.sdm_cases to authenticated;
grant select on public.audit_events to authenticated;
grant usage, select on sequence public.sdm_cases_id_seq to authenticated;

-- Profile hanya dapat dibaca akun sendiri; role tidak dapat diubah melalui aplikasi.
drop policy if exists own_profile_read on public.profiles;
create policy own_profile_read on public.profiles for select to authenticated using (id = (select auth.uid()));

DO $$ declare tbl text; begin
 foreach tbl in array array['bottlenecks','action_plans','bank_recap','sdm_cases'] loop
  execute format('drop policy if exists scoped_read on public.%I',tbl);
  execute format('drop policy if exists scoped_insert on public.%I',tbl);
  execute format('drop policy if exists scoped_update on public.%I',tbl);
  execute format('create policy scoped_read on public.%I for select to authenticated using ((select public.current_app_role()) in (''admin'',''editor'',''viewer''))',tbl);
  execute format('create policy scoped_insert on public.%I for insert to authenticated with check ((select public.current_app_role()) in (''admin'',''editor''))',tbl);
  execute format('create policy scoped_update on public.%I for update to authenticated using ((select public.current_app_role()) in (''admin'',''editor'')) with check ((select public.current_app_role()) in (''admin'',''editor''))',tbl);
 end loop;
end $$;
drop policy if exists admin_audit_read on public.audit_events;
create policy admin_audit_read on public.audit_events for select to authenticated using ((select public.current_app_role())='admin');

-- Catatan: personel pengelola profil dibuat melalui Supabase SQL Editor (service_role),
-- bukan oleh aplikasi. Matikan sign-up publik di Authentication > Providers > Email.

-- Template dasar, tidak memuat NIP atau identitas SDM.
insert into public.bottlenecks (no,kategori,risiko,tindak_lanjut,jalur,pic,koordinasi,prioritas,deadline,output,status,keputusan) values
(1,'Meninggal dunia','Tidak bisa autodebet; status kewajiban perlu ditelaah','Validasi kematian, NIP, nominal sisa; periksa hak/pembayaran terakhir; susun berkas kasus dan minta telaah hukum-keuangan','Putusan mekanisme penagihan/penanganan menurut ketentuan; tidak otomatis dibebankan ke keluarga','PSNK / Pokja Evkin','Biro Keuangan, Kepegawaian, APIP, Bagian Hukum','Kritis','2026-11-13','Berita acara verifikasi, dokumen kematian, telaah, keputusan tertulis','Belum Mulai','Tentukan mekanisme penanganan kasus meninggal dunia'),
(2,'Resign/PHK','Tidak ada gaji/tukin untuk pendebitan','Validasi SK pemberhentian; konfirmasi kontak; kirim surat tagihan resmi dan kode/kanal setor dari Keuangan','Setoran langsung ke kas negara melalui mekanisme resmi; eskalasi bila tidak membayar','PSNK / Katim','Kepegawaian, Biro Keuangan','Tinggi','2026-11-20','Surat tagihan, bukti diterima, bukti setor/NTPN','Belum Mulai','Setujui jalur penagihan bagi nonaktif'),
(3,'Pensiun','Tidak masuk payroll aktif','Verifikasi pensiun & nominal akhir; kirim pemberitahuan tertulis; tetapkan kanal setoran resmi','Setoran langsung; eskalasi keterlambatan ke pejabat berwenang','PSNK / Katim','Kepegawaian, Biro Keuangan','Tinggi','2026-11-20','SK pensiun, surat tagihan, bukti setor/NTPN','Belum Mulai','Tegaskan jalur non-payroll'),
(4,'Saldo tidak cukup','Autodebet gagal terus berulang','Kontak SDM; konfirmasi gaji/tukin berikutnya; lakukan debit ulang terjadwal atau tawarkan setoran resmi; catat bukti komunikasi','Autodebet ulang atau setoran langsung, sesuai ketentuan','Katim / Pokja Evkin','Bank terkait, Biro Keuangan','Kritis','2026-11-27','Daftar gagal, komitmen tertulis, berita acara eksekusi','Belum Mulai','Tentukan eskalasi untuk saldo kosong berulang'),
(5,'Rekening bermasalah','Rekening blokir/dormant/tutup/tidak aktif','Minta bank klasifikasi error; fasilitasi pembaruan status rekening; alihkan jalur jika autodebet tidak mungkin','Setoran langsung setelah konfirmasi bank/Keuangan','Katim / Bank','PSNK, Biro Keuangan','Tinggi','2026-11-13','Hasil pengecekan bank dan bukti solusi rekening','Belum Mulai','Setujui alternatif pembayaran'),
(6,'Data tidak cocok','NIP/nama/rekening tidak valid, gagal cocok BNBA','Rekonsiliasi NIP-nama-bank-rekening dengan sumber resmi; perbaiki BNBA; kirim ulang daftar','Ajukan ulang debit hanya setelah validasi','Pokja Evkin','Katim, Bank terkait','Tinggi','2026-10-30','BNBA koreksi, log perubahan, berita acara validasi','Belum Mulai','Penetapan data dasar final'),
(7,'Gagal berulang','Sebagian tunggakan terakumulasi','Hitung sisa per NIP dari ledger semua tahap; identifikasi gagal >1 kali; prioritaskan nominal besar','Debit Tahap VI/VII atau setoran langsung resmi','Pokja Evkin','Mandiri, BRI, BSI, Keuangan','Kritis','2026-11-30','Daftar akumulasi sisa, laporan realisasi netto per NIP','Belum Mulai','Persetujuan penjadwalan penyelesaian akhir'),
(8,'BRI/BSI belum diproses','Jadwal/dokumen debit belum pasti','Tetapkan jadwal dengan BRI/BSI; tuntaskan surat kuasa bila diperlukan; minta hasil debit per NIP','Autodebet bank sesuai kesepakatan dan ketentuan','PSNK / Biro Keuangan','Bank BRI dan BSI','Kritis','2026-11-13','Jadwal bank, konfirmasi berkas, hasil debit','Belum Mulai','Percepatan lintas bank'),
(9,'Selisih rekonsiliasi','Realisasi/setoran tidak sama dengan kewajiban','Cocokkan master final, mutasi debit, setoran langsung, NTPN; koreksi hanya dengan audit trail','Validasi penerimaan negara sebelum status lunas','Pokja Evkin / Keuangan','Bendahara, Bank, APIP','Tinggi','2026-12-15','Rekonsiliasi signed-off dan buku pembantu','Belum Mulai','Persetujuan angka final'),
(10,'Kasus lain','Sisa tunggakan tidak tertangani menjelang tutup tahun','Surat tagihan terakhir, eskalasi berdasarkan daftar kasus, susun rekomendasi sesuai ketentuan','Tindak lanjut resmi; tidak otomatis diakui lunas','PSNK / Pimpinan','Biro Keuangan, APIP, Bagian Hukum','Kritis','2026-12-15','Matriks pengecualian dan keputusan pejabat','Belum Mulai','Keputusan kasus belum lunas per 31 Desember')
on conflict (no) do nothing;

insert into public.action_plans (no,fase,kegiatan,langkah,pic,mulai,deadline,output,prioritas,status,progres) values
(1,'Pemetaan','Konsolidasi master kewajiban final','Satu NIP satu sisa; pisahkan Tukin dan Uang Makan','Pokja Evkin','2026-10-09','2026-10-16','Master final tervalidasi','Kritis','Belum Mulai',0),
(2,'Pemetaan','Tagging kendala seluruh SDM','Klasifikasi meninggal, resign, pensiun, saldo, rekening, dll','Katim / Pokja Evkin','2026-10-09','2026-10-23','BNBA terklasifikasi','Kritis','Belum Mulai',0),
(3,'Pemetaan','Validasi bank & rekening','Perbaiki data salah/rekening bermasalah sebelum proses ulang','Pokja Evkin / Bank','2026-10-12','2026-10-30','Daftar layak autodebet','Tinggi','Belum Mulai',0),
(4,'Debet','Penuntasan Mandiri Tahap VI','Ulangi 594 gagal (angka awal perlu validasi); rekonsiliasi hasil per NIP','Mandiri / Keuangan','2026-10-12','2026-10-30','Hasil debit VI','Kritis','Belum Mulai',0),
(5,'Debet','Percepatan Tahap BRI','Kejelasan jadwal, hasil debit, dan tindak lanjut 166 gagal tahap I','BRI / Keuangan','2026-10-12','2026-11-13','Hasil debit BRI & daftar gagal','Kritis','Belum Mulai',0),
(6,'Debet','Kelengkapan BSI','Selesaikan surat kuasa/dokumen dan jadwal eksekusi','BSI / Keuangan','2026-10-12','2026-11-13','Dokumen & jadwal disepakati','Kritis','Belum Mulai',0),
(7,'Kasus Khusus','Verifikasi meninggal dunia','Lengkapi dokumen; minta telaah hukum dan keuangan','PSNK / Keuangan','2026-10-19','2026-11-13','Daftar kasus & rekomendasi','Kritis','Belum Mulai',0),
(8,'Kasus Khusus','Tagihan SDM resign / pensiun','Kirim surat & fasilitasi setoran langsung','Katim / Keuangan','2026-10-19','2026-11-20','Tagihan dan jalur setor resmi','Tinggi','Belum Mulai',0),
(9,'Debet','Mandiri Tahap VII','Eksekusi siklus gaji November setelah Tahap VI','Mandiri / Keuangan','2026-11-02','2026-11-13','Hasil debit VII','Kritis','Belum Mulai',0),
(10,'Debet','Debit ulang / setoran alternatif','Tindak lanjut gagal berulang dan saldo kosong','Katim / Bank','2026-11-02','2026-11-30','Realisasi tambahan per NIP','Kritis','Belum Mulai',0),
(11,'Rekonsiliasi','Rekonsiliasi lintas bank','Gabung hasil Mandiri/BRI/BSI dan bukti setoran; periksa duplikasi','Pokja Evkin / Keuangan','2026-11-16','2026-11-30','Rekap netto per NIP','Tinggi','Belum Mulai',0),
(12,'Penagihan','Eskalasi kasus bermasalah','Surat tagihan akhir & rekomendasi pimpinan','PSNK / Keuangan','2026-11-16','2026-12-15','Keputusan per kasus','Kritis','Belum Mulai',0),
(13,'Pelunasan','Penuntasan tunggakan tersisa','Eksekusi autodebet/transfer resmi, konfirmasi bukti penerimaan','PSNK / Bank / Katim','2026-12-01','2026-12-15','Target seluruh kewajiban lunas','Kritis','Belum Mulai',0),
(14,'Penutupan','Verifikasi pelunasan per NIP','Bukti setor/NTPN, nominal, tanggal, klasifikasi status','Keuangan / Pokja Evkin','2026-12-07','2026-12-24','Daftar final lunas dan belum lunas','Kritis','Belum Mulai',0),
(15,'Penutupan','Laporan akhir & daftar pengecualian','Dokumentasi keputusan untuk setiap kasus yang belum lunas','PSNK / Pimpinan','2026-12-16','2026-12-31','Laporan akhir 31 Desember','Kritis','Belum Mulai',0)
on conflict (no) do nothing;

insert into public.bank_recap(bank,status) values ('Mandiri','Menunggu data rekonsiliasi'),('BRI','Menunggu data rekonsiliasi'),('BSI','Menunggu data rekonsiliasi') on conflict (bank) do nothing;

-- Jalankan sekali untuk mengaktifkan penambahan nomor otomatis dan arsip.
begin;
alter table public.bottlenecks add column if not exists deleted_at timestamptz;
create sequence if not exists public.bottlenecks_no_seq;
select setval('public.bottlenecks_no_seq', greatest(
 coalesce((select max(no) from public.bottlenecks),0),
 (select last_value from public.bottlenecks_no_seq),1),true);
alter sequence public.bottlenecks_no_seq owned by public.bottlenecks.no;
alter table public.bottlenecks alter column no set default nextval('public.bottlenecks_no_seq');
grant usage on sequence public.bottlenecks_no_seq to authenticated;
commit;
