import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import {PGlite} from '@electric-sql/pglite'
import {stageBatch,batchChanges,commitBatch} from '../src/import/batchTransport.js'
const db=new PGlite()
const editor='00000000-0000-0000-0000-000000000001',viewer='00000000-0000-0000-0000-000000000002'
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,role text);insert into auth.users values('${editor}','editor'),('${viewer}','viewer');create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create function public.current_app_role() returns text language sql stable security definer as $$select role from auth.users where id=auth.uid()$$;grant usage on schema auth to authenticated;grant execute on function auth.uid(),public.current_app_role() to authenticated;`)
await db.exec(fs.readFileSync('supabase/recovery-foundation.draft.sql','utf8'))
await db.exec(fs.readFileSync('supabase/recovery-batches.draft.sql','utf8'))
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${editor}',false)`)
let hash=0
const data=(amount=30,obligation=100)=>[{type:'person',data:{nip:'000000000000000001',nama:'Uji',bank:'Mandiri'}},{type:'obligation',data:{nip:'000000000000000001',bank:'Mandiri',kind:'TUKIN',year:2025,amount:obligation}},{type:'payment',data:{nip:'000000000000000001',bank:'Mandiri',kind:'TUKIN',year:2025,stage:1,amount}}]
async function batch(records=data(),totals={Mandiri:{obligation:100,payment:30}}){const digest=(++hash).toString(16).padStart(64,'0');const b=(await db.query('select recovery_begin($1,$2,$3,$4) id',['uji.xlsx',digest,records.length,JSON.stringify(totals)])).rows[0].id;await db.query('select recovery_append($1,$2)',[b,JSON.stringify(records)]);return b}
test('staging retry is idempotent; incomplete batch cannot validate',async()=>{const b=await batch();const retry=await db.query('select recovery_append($1,$2) added',[b,JSON.stringify(data())]);assert.equal(retry.rows[0].added,0);const empty=(await db.query('select recovery_begin($1,$2,3,$3) id',['uji.xlsx','a'.repeat(64),JSON.stringify({Mandiri:{obligation:100,payment:30}})])).rows[0].id;await assert.rejects(db.query('select recovery_validate($1)',[empty]),/INCOMPLETE_BATCH/)})
test('commit requires validation, then updates ledger and audit atomically',async()=>{const b=await batch();await assert.rejects(db.query('select recovery_commit($1,$2)',[b,'Uji']),/NOT_VALIDATED/);await db.query('select recovery_validate($1)',[b]);await db.query('select recovery_commit($1,$2)',[b,'Impor awal']);const q=await db.query('select nominal,verification from recovery_payments');assert.equal(q.rows.length,1);assert.equal(q.rows[0].verification,'pending');await db.query('select recovery_commit($1,$2)',[b,'Ulang']);assert.equal((await db.query('select count(*)::integer n from recovery_payments')).rows[0].n,1)})
test('conflicting chunk retries and recap mismatch are rejected',async()=>{const b=await batch();await assert.rejects(db.query('select recovery_append($1,$2)',[b,JSON.stringify(data(31))]),/CONFLICTING_RETRY/);const c=await batch(data(),{Mandiri:{obligation:100,payment:31}});await assert.rejects(db.query('select recovery_validate($1)',[c]),/RECAP_MISMATCH/)})
test('database preview returns exact correction amounts per NIP',async()=>{const b=await batch(data(25),{Mandiri:{obligation:100,payment:25}});const rows=(await db.query('select * from recovery_diff($1,0,50)',[b])).rows;assert.equal(rows.length,1);assert.equal(rows[0].record_type,'payment');assert.equal(rows[0].before_amount,30);assert.equal(rows[0].after_amount,25);assert.equal(rows[0].nip,'000000000000000001')})
test('correction requires reason and zero is recorded in audit',async()=>{const b=await batch(data(0),{Mandiri:{obligation:100,payment:0}});await db.query('select recovery_validate($1)',[b]);await assert.rejects(db.query('select recovery_commit($1,$2)',[b,'']),/REASON_REQUIRED/);await db.query('select recovery_commit($1,$2)',[b,'Koreksi hasil bank']);assert.equal((await db.query('select nominal from recovery_payments')).rows[0].nominal,0);assert.ok((await db.query('select count(*)::integer n from recovery_changes')).rows[0].n>=3)})
test('stale preview cannot overwrite a newer committed batch',async()=>{const first=await batch(data(1),{Mandiri:{obligation:100,payment:1}}),second=await batch(data(2),{Mandiri:{obligation:100,payment:2}});await db.query('select recovery_validate($1)',[first]);await db.query('select recovery_validate($1)',[second]);await db.query('select recovery_commit($1,$2)',[first,'Uji']);await assert.rejects(db.query('select recovery_commit($1,$2)',[second,'Uji']),/STALE_PREVIEW/)})
test('overpayment rejects whole batch',async()=>{const b=await batch(data(101),{Mandiri:{obligation:100,payment:101}});await assert.rejects(db.query('select recovery_validate($1)',[b]),/OVERPAYMENT/)})
test('late ledger failure rolls back master updates and audit together',async()=>{const records=data(0,0).slice(0,2);const b=await batch(records,{Mandiri:{obligation:0,payment:0}});await db.query('select recovery_validate($1)',[b]);const audit=(await db.query('select count(*)::integer n from recovery_changes')).rows[0].n;await assert.rejects(db.query('select recovery_commit($1,$2)',[b,'Uji rollback']),/LEDGER_OVERPAYMENT/);assert.equal((await db.query('select nominal from recovery_obligations')).rows[0].nominal,100);assert.equal((await db.query('select count(*)::integer n from recovery_changes')).rows[0].n,audit);assert.equal((await db.query('select status from recovery_imports where id=$1',[b])).rows[0].status,'validated')})
test('missing historical payment is retained and mismatched recap blocks commit',async()=>{const b=await batch(data().slice(0,2),{Mandiri:{obligation:100,payment:0}});await db.query('select recovery_validate($1)',[b]);await assert.rejects(db.query('select recovery_commit($1,$2)',[b,'Uji histori kosong']),/LIVE_RECAP_MISMATCH/);assert.equal((await db.query('select nominal from recovery_payments')).rows[0].nominal,1)})
test('viewer cannot start imports or write ledger directly',async()=>{await db.exec(`select set_config('request.jwt.claim.sub','${viewer}',false)`);await assert.rejects(batch(),/FORBIDDEN/);await assert.rejects(db.exec('update recovery_payments set nominal=99'),/permission denied/);await db.exec(`select set_config('request.jwt.claim.sub','${editor}',false)`);await assert.rejects(db.exec('update recovery_payments set nominal=99'),/permission denied/)})
test('browser transport stages reviews and commits against PostgreSQL functions',async()=>{
 const client={rpc:async(name,args)=>{try{
  const values=Object.values(args);const params=values.map((_,i)=>'$'+(i+1)).join(',');
  const q=await db.query(`select * from ${name}(${params})`,values.map(v=>typeof v==='object'?JSON.stringify(v):v));
  return {data:name==='recovery_diff'?q.rows:q.rows[0]?.[name]}
 }catch(error){return {error}}}}
 const normalized=data(5);const results=[{issues:[],people:[normalized[0].data],obligations:[normalized[1].data],payments:[normalized[2].data]}]
 const staged=await stageBatch(client,{fileName:'transport.xlsx',sha256:'f'.repeat(64),results,recap:{Mandiri:{obligation:100,payment:5}}})
 const diff=await batchChanges(client,staged.id);assert.equal(diff[0].before_amount,1);assert.equal(diff[0].after_amount,5)
 await commitBatch(client,staged.id,'Test transport');assert.equal((await db.query('select nominal from recovery_payments')).rows[0].nominal,5)
})
test.after(async()=>db.close())
