import React,{useState} from 'react'
import {stageBatch,batchChanges,commitBatch} from './batchTransport.js'
import {importErrorMessage} from './importErrors.js'
const rp=n=>n===null?'Baru':'Rp '+Number(n).toLocaleString('id-ID')
export default function BatchReview({client,snapshot,recap,onCommitted}){
 const production=client?.scope==='production'
 const [batch,setBatch]=useState(null),[rows,setRows]=useState([]),[offset,setOffset]=useState(0),[reviewed,setReviewed]=useState(false),[endSeen,setEndSeen]=useState(false),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(''),[done,setDone]=useState(false)
 const run=async task=>{setBusy(true);setError('');try{await task()}catch(e){setStatus('');setError(importErrorMessage(e))}finally{setBusy(false)}}
 const prepare=()=>run(async()=>{const result=await stageBatch(client,{...snapshot,recap,onProgress:(n,total)=>setStatus(`Menyiapkan ${n.toLocaleString('id-ID')} / ${total.toLocaleString('id-ID')} baris…`)});const changes=await batchChanges(client,result.id);setBatch(result);setRows(changes);setOffset(0);setEndSeen(changes.length<50);setReviewed(false);setStatus('Batch lolos validasi. Tinjau perubahan terhadap database sebelum menyimpan.')})
 const next=()=>run(async()=>{const nextOffset=offset+50;const changes=await batchChanges(client,batch.id,nextOffset);setRows(changes);setOffset(nextOffset);if(changes.length<50)setEndSeen(true)})
 const save=()=>run(async()=>{await commitBatch(client,batch.id,reason);setDone(true);setStatus(production?'Batch tersimpan di master produksi. Memuat ulang master aktif. Bukti penerimaan tetap perlu diverifikasi.':'Batch tersimpan di schema pengujian. Memuat ulang master aktif; data tetap memerlukan verifikasi bukti penerimaan.');await onCommitted?.()})
 const initial=production&&batch?.summary.initialImport===true
 if(!client)return <section className="panel" style={{marginTop:20}}><h2>Penyimpanan master</h2><p>Terkunci sampai jalur API schema pengujian diaktifkan dan diuji. Pemeriksaan Excel tetap dapat digunakan.</p></section>
 return <section className="panel" style={{marginTop:20}}><h2>{production?'Penyimpanan master produksi':'Uji penyimpanan master'}</h2><p>{production?'Tujuan: master produksi. Siapkan batch, tinjau rekap dan perubahan, lalu setujui penyimpanan.':'Tujuan: schema pengujian Supabase. Unggah ke staging, tinjau perubahan, lalu simpan sebagai satu transaksi.'}</p>{!batch&&<button className="btn secondary" disabled={busy} onClick={prepare}>{production?'Siapkan batch master produksi':'Siapkan batch pengujian'}</button>}{status&&<p role="status">{status}</p>}{error&&<p className="notice red-notice" role="alert">{error}</p>}{batch&&!done&&<>{initial&&<div className="notice amber-notice"><b>Impor awal: belum ada master sebelumnya.</b><p>{batch.summary.people.toLocaleString('id-ID')} SDM • {batch.summary.obligations.toLocaleString('id-ID')} record kewajiban • {batch.summary.payments.toLocaleString('id-ID')} record pengembalian.</p><p>Tinjau workbook sumber serta rekap bank dan tahun SP2D yang ditampilkan. Rincian di bawah tersedia untuk pemeriksaan; persetujuan impor awal memakai tinjauan sumber dan rekap.</p></div>}<h3>{initial?'Contoh rincian impor awal':'Perubahan terhadap database'} — halaman {offset/50+1}</h3><div className="table-scroll"><table><thead><tr><th>NIP</th><th>Jenis perubahan</th><th>Bank / Tahun / Tahap</th><th>Sebelum</th><th>Sesudah</th></tr></thead><tbody>{rows.map(r=><tr key={r.record_type+r.record_key}><td className="mono">{r.nip}</td><td>{r.record_type} / {r.kind}</td><td>{r.bank} / {r.year} / {r.stage||'—'}</td><td>{rp(r.before_amount)}</td><td>{rp(r.after_amount)}</td></tr>)}</tbody></table></div>{!rows.length&&<p>Tidak ada perubahan pada halaman ini.</p>}{rows.length===50&&<button className="btn secondary" disabled={busy} onClick={next}>Tinjau halaman berikutnya</button>}<label className="form-field"><span>Alasan impor atau koreksi</span><textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><label><input type="checkbox" checked={reviewed} disabled={!endSeen&&!initial} onChange={e=>setReviewed(e.target.checked)}/> {initial?'Workbook sumber serta rekap bank dan tahun SP2D telah ditinjau':'Seluruh halaman perubahan telah ditinjau'}</label><p>Penyimpanan diblokir jika data berubah sejak pratinjau atau saldo tidak cocok.</p><button className="btn primary" disabled={busy||!reviewed||!reason.trim()} onClick={save}>{production?'Simpan master produksi':'Simpan ke schema pengujian'}</button></>}</section>
}

