import React,{useEffect,useRef,useState} from 'react'
import BatchReview from './BatchReview.jsx'
import NonactivePreview from './NonactivePreview.jsx'
const rp=n=>'Rp '+Number(n||0).toLocaleString('id-ID')
export default function ImportPreview({onSnapshot,stagingClient=null}){
 const [file,setFile]=useState(null),[baseline,setBaseline]=useState(null),[report,setReport]=useState(null),[error,setError]=useState(''),[progress,setProgress]=useState('');const worker=useRef(null),snapshot=useRef(null)
 useEffect(()=>()=>worker.current?.terminate(),[])
 const cancel=()=>{worker.current?.terminate();worker.current=null;setProgress('')}
 const run=()=>{if(!file)return;cancel();setError('');setReport(null);setProgress('Menyiapkan pemeriksaan…');const task=new Worker(new URL('./preview.worker.js',import.meta.url),{type:'module'});worker.current=task;task.onmessage=({data})=>{if(data.type==='progress')setProgress(data.text);else{if(data.type==='done'){setReport(data.report);snapshot.current=data.snapshot;}else setError(data.message);cancel()}};task.onerror=()=>{setError('Pemeriksaan gagal. File mungkin terlalu besar atau formatnya tidak didukung.');cancel()};task.postMessage({file,baseline})}
 const select=(setter,f)=>{cancel();setReport(null);setError('');if(f&&!f.name.toLowerCase().endsWith('.xlsx')){setter(null);setError('Gunakan workbook .xlsx.');return}setter(f||null)}
 const blockers=report?report.banks.reduce((s,b)=>s+b.issueCount,0)+report.checks.issues.length+report.checks.overlaps:0
 return <><div className="page-title"><div><span className="eyebrow">TAHAP 2 • PEMERIKSAAN SUMBER</span><h1>Pratinjau Excel Master</h1><p>Periksa workbook kumulatif Mandiri, BRI, dan BSI. File asli dibaca di perangkat ini. Dalam mode pengujian, hasil pembacaan dapat dikirim ke schema pengujian melalui tombol penyimpanan.</p></div></div><section className="panel"><div className="notice amber-notice">{stagingClient?'Penyimpanan pengujian tersedia. Hasil pembacaan dikirim hanya setelah Anda menyiapkan batch; belum menjadi master aplikasi utama.':'Penyimpanan belum diaktifkan. Angka pengembalian berasal dari Excel dan belum diverifikasi dengan bukti penerimaan.'}</div><div className="form-grid"><label className="form-field"><span>Workbook terbaru (.xlsx)</span><input type="file" accept=".xlsx" onChange={e=>select(setFile,e.target.files?.[0])}/></label><label className="form-field"><span>Workbook sebelumnya (untuk perbandingan dan koreksi nol)</span><input type="file" accept=".xlsx" onChange={e=>select(setBaseline,e.target.files?.[0])}/></label></div><div className="toolbar" style={{marginTop:18}}><button className="btn primary" disabled={!file||!!progress} onClick={run}>Periksa workbook</button>{progress&&<button className="btn secondary" onClick={cancel}>Batalkan</button>}</div>{progress&&<p role="status" style={{marginTop:18}}>{progress}</p>}{error&&<p className="notice red-notice" role="alert" style={{marginTop:18}}>{error}</p>}</section>
 {report&&<><NonactivePreview summary={report.nonactive} review={report.nonactiveReview||[]} fileName={report.fileName}/><BatchReview key={report.sha256} client={blockers===0?stagingClient:null} snapshot={snapshot.current} recap={Object.fromEntries(report.banks.map(b=>[b.bank,{obligation:b.totals.obligation,payment:b.totals.payment}]))}/><section className="panel" style={{marginTop:20}}><h2>Hasil pemeriksaan</h2>{onSnapshot&&<button className="btn primary" disabled={blockers>0} onClick={()=>onSnapshot(snapshot.current)}>Buka master lokal & Monitoring SDM</button>}<p>{report.fileName}</p><p>{report.checks.people.toLocaleString('id-ID')} SDM • {blockers?`${blockers} masalah perlu diperiksa`:'Nominal cocok dengan rekap yang dibaca'}</p><p>{report.baselineName?'Pembanding: '+report.baselineName:'Belum ada workbook pembanding. Transaksi baru/koreksi belum dapat ditentukan.'}</p><div className="table-scroll"><table><thead><tr><th>Bank</th><th>SDM</th><th>Kewajiban</th><th>Pengembalian Excel</th><th>Sisa dihitung</th></tr></thead><tbody>{report.banks.map(b=><tr key={b.bank}><td>{b.bank}</td><td>{b.totals.people}</td><td>{rp(b.totals.obligation)}</td><td>{rp(b.totals.payment)}</td><td>{rp(b.totals.remaining)}</td></tr>)}</tbody></table></div>{report.checks.issues.map((x,i)=><p key={i} role="alert">{x.bank}: {x.code} — {x.measure}, Excel {rp(x.actual)}, rekap {rp(x.expected)}</p>)}{!!report.checks.overlaps&&<p role="alert">NIP ditemukan pada lebih dari satu bank. Periksa sebelum menyimpan.</p>}</section>
 {report.banks.map(b=><section className="panel" style={{marginTop:20}} key={b.bank}><h2>{b.bank} — rincian tahap</h2>{b.legacyDifference!==null&&b.legacyDifference!==0&&<div className="notice amber-notice" style={{marginTop:16}}>Kolom Sisa Tagihan berbeda {rp(Math.abs(b.legacyDifference))} dari sisa dihitung. Kolom tersebut tidak dipakai sebagai sumber saldo.</div>}{b.comparison&&<p>Transaksi baru: {b.comparison.newPayments} ({rp(b.comparison.newAmount)}) • Koreksi: {b.comparison.corrections} • Koreksi kewajiban: {b.comparison.obligationCorrections} • SDM baru: {b.comparison.newPeople} • Tahap baru: {b.comparison.newStages.join(', ')||'Tidak ada'} • Tidak muncul/kosong: {b.comparison.missing} (tidak otomatis dihapus).</p>}<div className="table-scroll"><table><thead><tr><th>Tahap</th><th>Pembayaran positif</th><th>Tukin</th><th>Uang Makan</th></tr></thead><tbody>{b.stages.map(s=><tr key={s.stage}><td>{s.stage}</td><td>{s.positive}</td><td>{rp(s.tukin)}</td><td>{rp(s.um)}</td></tr>)}</tbody></table></div>{!!b.details?.length&&<><h3>Detail perubahan per NIP</h3><p>Maksimal 50 baris per jenis perubahan. Semua koreksi tetap perlu ditinjau sebelum penyimpanan.</p><div className="table-scroll"><table><thead><tr><th>NIP</th><th>Perubahan</th><th>Jenis / Tahun</th><th>Tahap</th><th>Sebelum</th><th>Sesudah</th></tr></thead><tbody>{b.details.map((r,i)=><tr key={i}><td className="mono">{r.nip}</td><td>{r.type}</td><td>{r.kind} / {r.year}</td><td>{r.stage||'—'}</td><td>{r.before===null?'—':rp(r.before)}</td><td>{rp(r.after)}</td></tr>)}</tbody></table></div></>}{b.issues.map((x,i)=><p key={i} role="alert">{x.code}{x.row?` — baris ${x.row}`:''}{x.column?`, kolom ${x.column}`:''}</p>)}{b.issueCount>20&&<p>Ditampilkan 20 dari {b.issueCount} masalah.</p>}</section>)}<div className="notice amber-notice" style={{marginTop:20}}>Hasil ini hanya pratinjau. Belum ada pembaruan Monitoring SDM atau verifikasi SP2D, tanggal pembayaran, dan bukti.</div></>}
 </>
}




