import React,{useMemo,useState} from 'react'
import {selectNonactiveReview,nonactiveReviewExport} from './nonactive.js'
export default function NonactivePreview({summary,review=[],fileName=''}){
 const [filters,setFilters]=useState({status:'',category:'',search:''}),[page,setPage]=useState(0),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const selected=useMemo(()=>selectNonactiveReview(review,filters),[review,filters])
 const update=(key,value)=>{setFilters(old=>({...old,[key]:value}));setPage(0)}
 const exportReview=async()=>{setBusy(true);setError('');try{
  const {default:write}=await import('write-excel-file/browser'),data=nonactiveReviewExport(selected,summary?.issues)
  const cells=rows=>rows.map((row,i)=>row.map(v=>({value:v??'',type:typeof v==='number'?Number:String,...(i===0?{fontWeight:'bold',backgroundColor:'#E7F0FF'}:{})})))
  await write([{sheet:'Tinjauan SDM',data:cells(data.review)},{sheet:'Masalah Sumber',data:cells(data.issues)}]).toFile(`TukinUMrecovery-tinjauan-nonaktif-${filters.status||'semua'}-${filters.category||'semua'}.xlsx`)
 }catch{setError('Ekspor belum berhasil. Coba kembali setelah pemeriksaan workbook selesai.')}finally{setBusy(false)}}
 if(!summary)return <section className="panel" style={{marginTop:20}}><h2>SDM nonaktif</h2><p>Sheet master tidak aktif tidak ditemukan. Ketiadaan data ini tidak berarti seluruh SDM aktif.</p></section>
 return <section className="panel" style={{marginTop:20}}><h2>Pencocokan SDM nonaktif</h2><p>{summary.records} catatan • {summary.matched} cocok berdasarkan NIP • {summary.unmatched} belum cocok.</p><p>{Object.entries(summary.categories).map(([name,count])=>`${name}: ${count}`).join(' • ')}</p><p>Status ini berasal dari Excel dan hanya ditampilkan pada pratinjau lokal. Belum disimpan atau mengubah kasus monitoring.</p>{summary.unmatched>0&&<p className="notice amber-notice">Catatan yang belum cocok perlu ditinjau. Tidak ditambahkan otomatis sebagai SDM baru dan tidak dijumlahkan sebagai kewajiban tambahan.</p>}{summary.nameMismatches>0&&<p>{summary.nameMismatches} catatan memiliki perbedaan nama meskipun NIP cocok. Nama pada master bank dipertahankan.</p>}{summary.issues.length>0&&<p role="alert">{summary.issues.length} masalah pada daftar nonaktif perlu diperiksa; catatan yang tidak valid tidak ditandai.</p>}
 <p>Ekspor: {selected.length} catatan • {filters.status||'Semua hasil pencocokan'} • {filters.category||'Semua kategori'}{filters.search?' • Hasil pencarian':''}.</p><div className="toolbar"><button className="btn secondary" onClick={()=>setShow(v=>!v)}>{show?'Tutup daftar tinjauan':'Buka daftar tinjauan'}</button><button className="btn secondary" disabled={busy||!selected.length} onClick={exportReview}>{busy?'Menyiapkan Excel…':'Ekspor tinjauan sesuai filter'}</button>{(filters.status||filters.category||filters.search)&&<button className="btn secondary" onClick={()=>{setFilters({status:'',category:'',search:''});setPage(0)}}>Hapus filter tinjauan</button>}</div>
 {show&&<><p>Sumber: {fileName}. Tinjau sebelum menghubungkan dengan kasus monitoring. Tanggal sumber yang berupa angka Excel belum diubah menjadi tanggal.</p><div className="form-grid"><label className="form-field"><span>Cari NIP / nama sumber / nama master</span><input value={filters.search} onChange={e=>update('search',e.target.value)}/></label><label className="form-field"><span>Hasil pencocokan</span><select value={filters.status} onChange={e=>update('status',e.target.value)}><option value="">Semua</option>{['Cocok','Nama berbeda','Belum cocok','NIP ambigu'].map(v=><option key={v}>{v}</option>)}</select></label><label className="form-field"><span>Kategori nonaktif</span><select value={filters.category} onChange={e=>update('category',e.target.value)}><option value="">Semua</option>{Object.keys(summary.categories).map(v=><option key={v}>{v}</option>)}</select></label></div><p>{selected.length} catatan sesuai filter.</p><div className="table-scroll"><table><thead><tr><th>NIP</th><th>Nama sumber</th><th>Nama master / Bank</th><th>Kategori</th><th>Hasil pencocokan</th><th>Tanggal sumber</th></tr></thead><tbody>{selected.slice(page*15,page*15+15).map(r=><tr key={r.nip}><td className="mono">{r.nip}</td><td>{r.nama}</td><td>{r.masterName||'—'}<small>{r.bank||'Belum cocok'}</small></td><td>{r.category}</td><td>{r.matchStatus}</td><td>{String(r.endDateRaw??'—')}</td></tr>)}{!selected.length&&<tr><td colSpan="6">Tidak ada catatan sesuai filter.</td></tr>}</tbody></table></div><div className="pagination"><span>Halaman {page+1}</span><div><button className="btn secondary" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Sebelumnya</button><button className="btn secondary" disabled={(page+1)*15>=selected.length} onClick={()=>setPage(p=>p+1)}>Berikutnya</button></div></div></>}{error&&<p className="notice red-notice" role="alert">{error}</p>}</section>
}
