import React,{useState} from 'react'
import {prepareReferences,commitReferences} from './caseApi.js'
import {loadLinkedCaseRows} from './linkedCases.js'
import LinkedCaseMonitor from './LinkedCaseMonitor.jsx'
export default function CaseReferencePanel({client,snapshot,rows,isAdmin=false}){
 const production=client?.scope==='production'
 const [search,setSearch]=useState(''),[batch,setBatch]=useState(null),[reason,setReason]=useState(''),[approved,setApproved]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[monitor,setMonitor]=useState(null),[done,setDone]=useState(false)
 const selected=rows.filter(r=>!r.issues.length&&[r.nip,r.manual.nama].some(v=>String(v||'').toLowerCase().includes(search.toLowerCase())))
 const run=async fn=>{setBusy(true);setError('');setMessage('');try{await fn()}catch{setError('Operasi belum berhasil dikonfirmasi. Master atau kasus mungkin berubah; muat ulang pratinjau dan monitoring sebelum mencoba kembali.')}finally{setBusy(false)}}
 if(!client)return <p>API referensi belum diaktifkan.</p>
 return <section className="panel"><h3>{production?'Hubungkan kasus ke master produksi':'Monitoring referensi pengujian'}</h3><p>{production?'Referensi kasus memakai master produksi yang telah disimpan.':'Referensi disimpan ke schema pengujian.'} Data penanganan dan nominal manual dipertahankan.</p>{isAdmin&&!batch&&<><label className="form-field"><span>Pilih kasus melalui pencarian NIP / nama</span><input value={search} onChange={e=>setSearch(e.target.value)}/></label><p>{selected.length} kasus yang lolos tinjauan akan masuk batch. Kasus yang ditahan tidak disertakan.</p><button className="btn secondary" disabled={busy||snapshot.source!=='database'||!selected.length||selected.length>500} onClick={()=>run(async()=>{const id=await prepareReferences(client,snapshot,selected);setBatch({id,count:selected.length});setMessage('Batch diperiksa di server. Tinjau pilihan kasus lalu beri alasan persetujuan.')})}>{production?'Siapkan penghubungan kasus':'Siapkan referensi pengujian'}</button>{snapshot.source!=='database'&&<p>Gunakan master tersimpan untuk menyiapkan referensi.</p>}</>}{isAdmin&&batch&&!done&&<><p>Batch mencakup {batch.count} kasus dari pilihan yang telah diperiksa.</p><label className="form-field"><span>Alasan persetujuan referensi</span><textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><label><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/> Saya sudah meninjau pilihan kasus dan data manual yang dipertahankan.</label><button className="btn primary" disabled={busy||!approved||!reason.trim()} onClick={()=>run(async()=>{const result=await commitReferences(client,batch.id,reason);setDone(true);setMessage(`${result.linked} referensi disimpan; ${result.alreadyLinked} sudah terhubung. Data manual dipertahankan.`)})}>{production?'Simpan penghubungan kasus':'Simpan referensi pengujian'}</button></>}{!isAdmin&&<p>Penghubungan hanya dapat diubah oleh admin.</p>}<button className="btn secondary" disabled={busy} onClick={()=>run(async()=>setMonitor(await loadLinkedCaseRows(client)))}>Muat monitoring referensi tersimpan</button>{message&&<p role="status">{message}</p>}{error&&<p className="notice red-notice" role="alert">{error}</p>}{monitor&&<LinkedCaseMonitor serverRows={monitor.rows} scope={client.scope}/>}</section>
}
