import React,{useEffect,useMemo,useRef,useState} from 'react'
import {loadStoredSnapshot} from '../import/batchTransport.js'
import {previewCaseLinks,loadManualCases,caseLinkExport,simulationCases} from './caseLinks.js'
import {detailBalances} from './progress.js'
import LinkedCaseMonitor from './LinkedCaseMonitor.jsx'
import CaseReferencePanel from './CaseReferencePanel.jsx'
const rp=n=>n===null||n===undefined||n===''?'Belum tersedia':'Rp '+Number(n).toLocaleString('id-ID')
const emptyRows=[]
export default function CaseLinkPreview({snapshot,masterClient,manualClient,manualRows=emptyRows,demo=false,caseClient=null,onImport}){
 const [open,setOpen]=useState(false),[simulate,setSimulate]=useState(false),[data,setData]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[filter,setFilter]=useState(''),[page,setPage]=useState(0),[detail,setDetail]=useState(null),[exporting,setExporting]=useState(false)
 const request=useRef(0)
 useEffect(()=>{
  if(!open)return
  const id=++request.current;setLoading(true);setData(null);setError('');setPage(0);setDetail(null)
  Promise.all([snapshot?Promise.resolve(snapshot):masterClient?loadStoredSnapshot(masterClient):Promise.resolve(null),simulate?Promise.resolve(simulationCases):manualClient?loadManualCases(manualClient):Promise.resolve(manualRows)]).then(([source,cases])=>{if(request.current===id)setData(source?{source,plan:previewCaseLinks(source,cases)}:null)}).catch(()=>{if(request.current===id)setError('Pratinjau belum dapat dimuat. Periksa koneksi dan muat ulang; tidak ada perubahan yang disimpan.')} ).finally(()=>{if(request.current===id)setLoading(false)})
  return()=>{request.current++}
 },[open,snapshot,masterClient,manualClient,manualRows,simulate,attempt])
 const rows=useMemo(()=>data?.plan.rows.filter(r=>!filter||(filter==='held'?r.issues.length>0:r.issues.length===0))||[],[data,filter])
 const exportPlan=async()=>{setExporting(true);setError('');try{const {default:write}=await import('write-excel-file/browser');const tables=caseLinkExport({...data.plan,rows});const cells=r=>r.map((row,i)=>row.map(v=>({value:v??'',type:typeof v==='number'?Number:String,...(i===0?{fontWeight:'bold',backgroundColor:'#E7F0FF'}:{})})));await write([{sheet:'Kasus dan Master',data:cells(tables.cases)},{sheet:'Sumber tanpa Kasus',data:cells(tables.candidates)}]).toFile(`TukinUMrecovery-pratinjau-kasus-${simulate?'simulasi':'sumber'}-${filter||'semua'}.xlsx`)}catch{setError('Ekspor pratinjau belum berhasil. Coba kembali.')}finally{setExporting(false)}}
 return <section className="panel" style={{marginBottom:20}}><h2>Pratinjau hubungan master dan kasus</h2><p>Periksa penghubungan berdasarkan NIP. Status, PIC, deadline, bukti dan catatan manual dipertahankan. Tidak ada perubahan atau kasus baru yang disimpan.</p><div className="toolbar"><button className="btn secondary" onClick={()=>setOpen(v=>!v)}>{open?'Tutup pratinjau hubungan':'Buka pratinjau hubungan'}</button>{open&&<><button className="btn secondary" disabled={loading} onClick={()=>setAttempt(n=>n+1)}>Muat ulang pratinjau</button><button className="btn secondary" onClick={onImport}>Periksa Excel master</button>{demo&&<button className="btn secondary" onClick={()=>setSimulate(v=>!v)}>{simulate?'Kembali ke kasus lokal':'Gunakan kasus simulasi'}</button>}</>}</div>{open&&loading&&<p role="status">Memuat master dan daftar lengkap kasus…</p>}{open&&error&&<p className="notice red-notice" role="alert">{error}</p>}{open&&!loading&&!data&&!error&&<p>Belum ada master untuk dibandingkan. Periksa workbook terlebih dahulu.</p>}
 {open&&data&&<><p>Sumber master: {data.source.fileName}. Kasus: {simulate?'SIMULASI, bukan kasus tersimpan':manualClient?'Monitoring SDM tersimpan':'kasus lokal sesi ini'}.</p><p>{data.plan.summary.cases} kasus • {data.plan.summary.linkable} dapat ditinjau untuk dihubungkan • {data.plan.summary.held} ditahan • {data.plan.summary.candidates} catatan nonaktif tanpa kasus.</p><p>{caseClient?(caseClient.scope==='production'?'Penghubungan ke master produksi tersedia. Revisi master dan isi kasus diperiksa ulang sebelum menyimpan.':'API referensi pengujian tersedia. Revisi master dan isi kasus diperiksa ulang sebelum menyimpan.'):'Penyimpanan referensi belum diaktifkan. Pratinjau ini tidak menyimpan perubahan.'}</p><div className="notice amber-notice">Perbedaan nama/bank, NIP ambigu, kasus arsip dan status lunas yang belum didukung master ditahan untuk pemeriksaan. Catatan nonaktif tanpa kasus tidak otomatis menjadi kasus/tagihan.</div><div className="toolbar"><label className="form-field"><span>Hasil hubungan kasus</span><select value={filter} onChange={e=>{setFilter(e.target.value);setPage(0)}}><option value="">Semua kasus</option><option value="ready">Dapat ditinjau untuk dihubungkan</option><option value="held">Ditahan untuk pemeriksaan</option></select></label><button className="btn secondary" disabled={exporting} onClick={exportPlan}>{exporting?'Menyiapkan Excel…':'Ekspor pratinjau hubungan'}</button>{!caseClient&&<button className="btn secondary" disabled>Simpan referensi (belum aktif)</button>}</div><div className="table-scroll"><table><thead><tr><th>NIP / Nama</th><th>Nominal kasus manual</th><th>Nominal master</th><th>Penanganan manual</th><th>Hasil pratinjau</th><th>Rincian</th></tr></thead><tbody>{rows.slice(page*15,page*15+15).map((r,i)=><tr key={r.manual.id||r.nip+i}><td className="mono">{r.nip}<small>{r.manual.nama}</small></td><td>Kewajiban {rp(r.manual.kewajiban_total)}<small>Pengembalian {rp(r.manual.realisasi_total)}</small></td><td>Kewajiban {rp(r.master?.obligation)}<small>Pengembalian {rp(r.master?.payment)}</small><small>Sisa {rp(r.master?.remaining)}</small></td><td>{r.manual.status||'Belum diisi'}<small>PIC: {r.manual.pic||'Belum diisi'}</small><small>Deadline: {r.manual.deadline||'Belum diisi'}</small><small>{r.manual.catatan}</small></td><td>{r.action}<small>{r.issues.join('; ')}</small></td><td><button className="btn secondary" disabled={!r.master} onClick={()=>setDetail(r)}>Rincian master</button></td></tr>)}{!rows.length&&<tr><td colSpan="6">Tidak ada kasus manual sesuai filter. Catatan nonaktif tanpa kasus tersedia pada ekspor untuk ditinjau.</td></tr>}</tbody></table></div><div className="pagination"><span>{rows.length} kasus • Halaman {page+1}</span><div><button className="btn secondary" disabled={!page} onClick={()=>setPage(p=>p-1)}>Sebelumnya</button><button className="btn secondary" disabled={(page+1)*15>=rows.length} onClick={()=>setPage(p=>p+1)}>Berikutnya</button></div></div>
 {detail&&<><h3>{detail.master.nama} — rincian master</h3><button className="btn secondary" onClick={()=>setDetail(null)}>Tutup rincian</button><div className="table-scroll"><table><thead><tr><th>Jenis / Tahun</th><th>Kewajiban</th><th>Pengembalian</th><th>Sisa</th></tr></thead><tbody>{detailBalances(detail.master).map(r=><tr key={r.kind+r.year}><td>{r.kind} / {r.year}</td><td>{rp(r.amount)}</td><td>{rp(r.payment)}</td><td>{rp(r.remaining)}</td></tr>)}</tbody></table></div><div className="table-scroll"><table><thead><tr><th>Tahap</th><th>Jenis / Tahun</th><th>Nominal</th><th>Verifikasi</th></tr></thead><tbody>{detail.master.payments.map((r,i)=><tr key={i}><td>{r.stage}</td><td>{r.kind} / {r.year}</td><td>{rp(r.amount)}</td><td>{r.verification==='verified'?'Terverifikasi':'Belum diverifikasi'}</td></tr>)}</tbody></table></div></>}
 {!simulate&&<CaseReferencePanel key={String(data.source.revision)+attempt} client={caseClient} snapshot={data.source} rows={data.plan.rows}/>}
 {simulate&&<LinkedCaseMonitor snapshot={data.source} cases={simulationCases} links={simulationCases.slice(0,2).map(c=>({case_id:c.id,nip:c.nip,master_revision:0}))} simulation/>}
 </>}
 </section>
}


