import React,{useMemo,useState} from 'react'
import {linkedCaseRows,linkedCaseExport} from './linkedCases.js'
export default function LinkedCaseMonitor({snapshot,cases,links,simulation=false,serverRows=null,scope=null}){
 const [search,setSearch]=useState(''),[source,setSource]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const rows=useMemo(()=>serverRows||linkedCaseRows(snapshot,cases,links,{simulation}),[serverRows,snapshot,cases,links,simulation])
 const selected=rows.filter(r=>(!source||r.source===source)&&(!search||[r.manual.nip,r.manual.nama,r.manual.pic].some(v=>String(v||'').toLowerCase().includes(search.toLowerCase()))))
 const rp=n=>n===null||n===undefined?'Belum tersedia':'Rp '+Number(n).toLocaleString('id-ID')
 const exportRows=async()=>{setBusy(true);setError('');try{const {default:write}=await import('write-excel-file/browser');const cells=linkedCaseExport(selected).map((row,i)=>row.map(v=>({value:v,type:typeof v==='number'?Number:String,...(i===0?{fontWeight:'bold',backgroundColor:'#E7F0FF'}:{})})));await write([{sheet:'Monitoring Terhubung',data:cells}]).toFile(`TukinUMrecovery-monitoring-terhubung-${simulation?'simulasi':scope==='production'?'produksi':'pengujian'}.xlsx`)}catch{setError('Ekspor monitoring belum berhasil. Coba kembali.')}finally{setBusy(false)}}
 return <section className="panel" style={{marginTop:20}}><h3>Monitoring melalui referensi {simulation?'simulasi':'tersimpan'}</h3><p>{simulation?'Contoh lokal; referensi ini tidak tersimpan di database.':'Nominal master dibaca melalui referensi yang disetujui.'} Pengembalian sumber dan penerimaan terverifikasi ditampilkan terpisah. Status penanganan manual tetap dipertahankan.</p><div className="form-grid"><label className="form-field"><span>Cari monitoring terhubung</span><input value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="form-field"><span>Sumber nominal monitoring</span><select value={source} onChange={e=>setSource(e.target.value)}><option value="">Semua sumber</option>{[...new Set(rows.map(r=>r.source))].map(v=><option key={v}>{v}</option>)}</select></label></div><p>{selected.length} kasus sesuai filter.</p><button className="btn secondary" disabled={busy} onClick={exportRows}>{busy?'Menyiapkan Excel…':'Ekspor monitoring terhubung'}</button>{error&&<p role="alert" className="notice red-notice">{error}</p>}<div className="table-scroll"><table><thead><tr><th>SDM</th><th>Sumber nominal</th><th>Kewajiban / Pengembalian</th><th>Sisa / Terverifikasi</th><th>Penanganan manual</th><th>Pemeriksaan</th></tr></thead><tbody>{selected.map(r=><tr key={r.manual.id}><td className="mono">{r.manual.nip}<small>{r.manual.nama}</small></td><td>{r.source}</td><td>{rp(r.finance?.obligation)}<small>Pengembalian sumber {rp(r.finance?.payment)}</small></td><td>{rp(r.finance?.remaining)}<small>Terverifikasi {rp(r.finance?.verified)}</small></td><td>{r.manual.status}<small>PIC: {r.manual.pic||'Belum diisi'}</small><small>{r.manual.deadline||'Deadline belum diisi'}</small><small>{r.manual.catatan}</small></td><td>{r.warnings.join('; ')||'Referensi sesuai sumber yang dimuat'}</td></tr>)}</tbody></table></div></section>
}
