import React,{useMemo,useState,useDeferredValue} from 'react'
import {indexSnapshot,selectProgress,detailBalances,exportRows} from './progress.js'
const rp=n=>'Rp '+Number(n||0).toLocaleString('id-ID')
export default function RecoveryMonitor({snapshot,onImport}){
 const [filters,setFilters]=useState({bank:'',year:'',kind:'',stage:'',search:''}),[page,setPage]=useState(0),[detail,setDetail]=useState(null),[exporting,setExporting]=useState(false),[error,setError]=useState('')
 const deferredSearch=useDeferredValue(filters.search)
 const index=useMemo(()=>indexSnapshot(snapshot?.results||[]),[snapshot])
 const selection=useMemo(()=>selectProgress(index,{...filters,search:deferredSearch}),[index,filters.bank,filters.year,filters.kind,filters.stage,deferredSearch])
 const years=useMemo(()=>[...new Set(index.obligations.map(r=>r.year))].sort(),[index]),stages=useMemo(()=>[...new Set(index.payments.map(r=>r.stage))].sort((a,b)=>a-b),[index])
 const update=(key,value)=>{setFilters(old=>({...old,[key]:value}));setPage(0);setDetail(null)}
 const exportExcel=async()=>{setExporting(true);setError('');try{const {default:write}=await import('write-excel-file/browser');const data=exportRows(selection,filters.stage);const cells=rows=>rows.map((row,i)=>row.map(v=>({value:v??'',type:typeof v==='number'?Number:String,...(i===0?{fontWeight:'bold',backgroundColor:'#E7F0FF'}:{})})));await write([{sheet:'Monitoring SDM',data:cells(data.summary)},{sheet:'Pengembalian per tahap',data:cells(data.transactions)}]).toFile(`TukinUMrecovery-${filters.bank||'semua-bank'}-${filters.year||'semua-tahun'}-${filters.kind||'Tukin-UM'}-${filters.stage?'tahap-'+filters.stage:'semua-tahap'}.xlsx`)}catch(e){setError(e.message)}finally{setExporting(false)}}
 if(!snapshot)return <section className="panel"><h1>Master & Progres Pengembalian</h1><p>Periksa workbook terlebih dahulu untuk memuat master lokal.</p><button className="btn primary" onClick={onImport}>Buka pratinjau Excel</button></section>
 const totals=selection.totals,rows=selection.rows.slice(page*25,page*25+25)
 return <><div className="page-title"><div><span className="eyebrow">{snapshot.source==='database'?'MASTER TERSIMPAN • PENGUJIAN':'TAHAP 4 • MASTER LOKAL'}</span><h1>Monitoring SDM & Progres</h1><p>Sumber: {snapshot.fileName}. {snapshot.source==='database'?'Data dimuat dari Supabase; revisi '+snapshot.revision+'.':'Data hanya di memori sesi ini, belum tersimpan ke Supabase.'}</p></div><button className="btn secondary" disabled={exporting||!selection.rows.length} onClick={exportExcel}>{exporting?'Menyiapkan Excel…':'Ekspor XLSX sesuai filter'}</button></div><div className="notice amber-notice">Pengembalian Excel belum diverifikasi dengan bukti. Tahun yang dipilih adalah tahun kewajiban; tanggal/tahun pengembalian dan SP2D belum dipetakan.</div>{error&&<p role="alert" className="notice red-notice">{error}</p>}
 <section className="panel"><div className="form-grid"><label className="form-field"><span>Cari NIP / nama / provinsi</span><input value={filters.search} onChange={e=>update('search',e.target.value)}/></label>{[['bank','Bank',['Mandiri','BRI','BSI']],['year','Tahun kewajiban',years],['kind','Jenis',['TUKIN','UM']],['stage','Tahap',stages]].map(([key,label,options])=><label className="form-field" key={key}><span>{label}</span><select value={filters[key]} onChange={e=>update(key,e.target.value)}><option value="">Semua</option>{options.map(v=><option key={v} value={v}>{v}</option>)}</select></label>)}</div></section>
 <div className="stats-grid" style={{marginTop:20}}>{[['SDM sesuai filter',totals.people.toLocaleString('id-ID')],['Kewajiban',rp(totals.obligation)],['Pengembalian Excel',rp(totals.payment)],['Sisa menurut Excel',rp(totals.remaining)],['Penerimaan terverifikasi',rp(totals.verified)],['Capaian menurut Excel',totals.pct.toLocaleString('id-ID',{minimumFractionDigits:2,maximumFractionDigits:2})+'%']].map(([label,value])=><div className="stat-card" key={label}><div className="stat-head">{label}</div><strong>{value}</strong></div>)}</div>{filters.stage&&<div className="notice demo-notice">Tahap {filters.stage}: {rp(totals.stagePayment)}. Daftar dibatasi pada SDM dengan pembayaran positif pada tahap ini; sisa tetap memperhitungkan seluruh tahap.</div>}
 <section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>SDM / Wilayah</th><th>Bank</th><th>Kewajiban</th><th>Pengembalian Excel</th><th>Sisa</th><th>Detail</th></tr></thead><tbody>{rows.map(p=><tr key={p.nip}><td><b>{p.nama}</b><small className="mono">{p.nip}</small><small>{p.provinsi}</small></td><td>{p.bank}</td><td>{rp(p.obligation)}</td><td>{rp(p.payment)}</td><td>{rp(p.remaining)}</td><td><button className="btn secondary" onClick={()=>setDetail(p)}>Riwayat</button></td></tr>)}{!rows.length&&<tr><td colSpan="6" className="empty">Tidak ada SDM sesuai filter.</td></tr>}</tbody></table></div><div className="pagination"><span>{totals.people} SDM • Halaman {page+1}</span><div><button className="btn secondary" disabled={!page} onClick={()=>setPage(p=>p-1)}>Sebelumnya</button><button className="btn secondary" disabled={(page+1)*25>=totals.people} onClick={()=>setPage(p=>p+1)}>Berikutnya</button></div></div></section>
 {detail&&<section className="panel" style={{marginTop:20}}><div className="panel-heading"><h2>{detail.nama} — {detail.nip}</h2><button className="btn secondary" onClick={()=>setDetail(null)}>Tutup riwayat</button></div><h3 style={{marginTop:20}}>Kewajiban per jenis dan tahun</h3><div className="table-scroll"><table><thead><tr><th>Jenis</th><th>Tahun</th><th>Kewajiban</th><th>Pengembalian Excel</th><th>Sisa</th></tr></thead><tbody>{detailBalances(detail).map(r=><tr key={r.kind+r.year}><td>{r.kind}</td><td>{r.year}</td><td>{rp(r.amount)}</td><td>{rp(r.payment)}</td><td>{rp(r.remaining)}</td></tr>)}</tbody></table></div><h3>Riwayat seluruh tahap untuk filter tahun/jenis</h3><div className="table-scroll"><table><thead><tr><th>Tahap</th><th>Jenis / Tahun</th><th>Nominal</th><th>Verifikasi</th></tr></thead><tbody>{detail.payments.map((r,i)=><tr key={i}><td>{r.stage}</td><td>{r.kind} / {r.year}</td><td>{rp(r.amount)}</td><td>{r.verification==='verified'?'Terverifikasi':'Belum diverifikasi'}</td></tr>)}</tbody></table></div></section>}
 </>
}

