import React, {useState, useEffect, useMemo, useCallback} from 'react'
import {createRoot} from 'react-dom/client'
import {createClient} from '@supabase/supabase-js'
import readXlsxFile from 'read-excel-file'
import {LayoutDashboard, Users, AlertTriangle, CalendarDays, Landmark, FileSpreadsheet, LogOut, ShieldCheck, Search, Plus, RefreshCw, Upload, Download, Menu, X, CheckCircle2, Clock3, TrendingUp, Info, LoaderCircle, Pencil, ChevronLeft, ChevronRight, LockKeyhole, FileCheck2, Filter, Eye, Bell, CircleHelp, HeartHandshake} from 'lucide-react'
import seeds from './seed.json'
import './style.css'

const url = import.meta.env.VITE_SUPABASE_URL
const key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY
const configured = Boolean(url && key && !url.includes('PROJECT_ID'))
const supabase = configured ? createClient(url, key, { auth: {persistSession:true, autoRefreshToken:true, detectSessionInUrl:true} }) : null
const fmtRp = n => 'Rp ' + Math.max(0,Number(n||0)).toLocaleString('id-ID', {maximumFractionDigits:0})
const fmtN = n => Number(n||0).toLocaleString('id-ID')
const safeDate = v => v ? new Date(`${v}T12:00:00`).toLocaleDateString('id-ID', {day:'2-digit', month:'short', year:'numeric'}) : '—'
const deadline = '2026-12-31'
const menus = [
  {id:'dashboard',name:'Dashboard',icon:LayoutDashboard},
  {id:'kasus',name:'Monitoring SDM',icon:Users},
  {id:'bottleneck',name:'Matriks Bottleneck',icon:AlertTriangle},
  {id:'aksi',name:'Rencana Aksi',icon:CalendarDays},
  {id:'bank',name:'Rekap Bank',icon:Landmark},
  {id:'panduan',name:'Petunjuk',icon:CircleHelp}
]
const statuses = ['Belum Mulai','Proses','Menunggu Keputusan','Selesai','Tertunda']
const statusesCase = ['Belum Ditindaklanjuti','Proses Penagihan','Menunggu Autodebet','Perlu Telaah','Lunas Terverifikasi','Belum Lunas']
const banks = ['Mandiri','BRI','BSI','Lainnya']
const kategoriList = seeds.bottlenecks.map(x=>x.kategori)
const initCase = {nip:'',nama:'',provinsi:'',kab_kota:'',bank:'Mandiri',kategori:'Saldo tidak cukup',kewajiban_total:'',realisasi_total:'0',tahap_terakhir:'',jalur_penyelesaian:'',pic:'',deadline:'2026-12-15',status:'Belum Ditindaklanjuti',bukti:'',tanggal_pembayaran:'',catatan:''}
const bankDefaults = ['Mandiri','BRI','BSI'].map(bank=>({bank,jumlah_sdm:null,kewajiban_total:null,realisasi_netto:null,gagal_terakhir:null,cutoff:null,status:'Menunggu data rekonsiliasi',bukti:'',catatan:''}))
function notify(e) { return typeof e === 'string' ? e : (e?.message || 'Terjadi kesalahan. Periksa koneksi atau hak akses.') }
function Pill({value}) {const s=String(value||'Belum Mulai').toLowerCase(); const cls=s.includes('lunas')&&!s.includes('belum')||s==='selesai'?'green':s.includes('proses')||s.includes('autodebet')?'blue':s.includes('kritis')||s.includes('belum')||s.includes('tertunda')?'red':s.includes('tinggi')||s.includes('menunggu')||s.includes('telaah')?'amber':'slate';return <span className={'pill '+cls}>{value||'Belum Mulai'}</span>}
function IconCard({title,value,subtitle,icon:Icon,accent='navy'}) {return <div className={'stat-card '+accent}><div className="stat-head"><span>{title}</span><Icon size={18}/></div><strong>{value}</strong><small>{subtitle}</small></div>}
function Modal({title,children,onClose,footer}) {return <div className="modal-mask" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-top"><h3>{title}</h3><button className="icon-btn" onClick={onClose} aria-label="Tutup"><X size={20}/></button></div><div className="modal-main">{children}</div>{footer&&<div className="modal-bottom">{footer}</div>}</div></div>}
function Login({onSignIn,loginError,busy}) {const[email,setEmail]=useState('');const[password,setPassword]=useState('');return <div className="auth-screen"><div className="auth-art"><div className="large-mark"><ShieldCheck size={36}/></div><span className="eyebrow white">DIT. PERLINDUNGAN SOSIAL NON KEBENCANAAN</span><h1>Pengembalian yang terkendali.<br/><em>Keputusan yang tercatat.</em></h1><p>Monitor progres penyelesaian Tukin dan Uang Makan ASN PPPK TA 2025 sampai 31 Desember 2026.</p><div className="auth-metrics"><div><strong>10</strong><span>kategori bottleneck</span></div><div><strong>15</strong><span>rencana aksi</span></div><div><strong>31 Des</strong><span>batas penyelesaian</span></div></div></div><div className="auth-form-wrap"><div className="auth-form"><div className="mobile-logo"><ShieldCheck size={26}/></div><span className="eyebrow">AKSES INTERNAL TERBATAS</span><h2>Masuk ke TukinUMrecovery</h2><p>Gunakan akun yang telah diberikan oleh administrator. Pendaftaran mandiri tidak disediakan.</p><form onSubmit={e=>{e.preventDefault();onSignIn(email,password)}}><label>Alamat email<input autoComplete="username" type="email" value={email} required onChange={e=>setEmail(e.target.value)} placeholder="nama@kemensos.go.id"/></label><label>Kata sandi<input autoComplete="current-password" type="password" value={password} required onChange={e=>setPassword(e.target.value)} placeholder="Masukkan kata sandi"/></label>{loginError&&<div className="notice red-notice">{loginError}</div>}<button type="submit" disabled={busy} className="btn primary wide">{busy?<LoaderCircle className="spin" size={17}/>:<LockKeyhole size={17}/>} Masuk aplikasi</button></form><small>Data kewajiban bersifat internal. Jangan membagikan akun atau memasukkan data riil pada lingkungan uji.</small></div></div></div>}
function App(){
 const [session,setSession]=useState(null); const [profile,setProfile]=useState(null); const [authLoading,setAuthLoading]=useState(configured); const [loginError,setLoginError]=useState(''); const [busy,setBusy]=useState(false)
 const [page,setPage]=useState('dashboard');const [navOpen,setNavOpen]=useState(false)
 const [editingMatrix,setEditingMatrix]=useState(null);const [deletingMatrix,setDeletingMatrix]=useState(null);const [matrixError,setMatrixError]=useState('');
 const [matrix,setMatrix]=useState(seeds.bottlenecks); const [actions,setActions]=useState(seeds.actions); const [bankData,setBankData]=useState(bankDefaults)
 const [cases,setCases]=useState([]);const [caseTotal,setCaseTotal]=useState(0);const [caseSearchTotal,setCaseSearchTotal]=useState(0);const [openTotal,setOpenTotal]=useState(0);const [casesPage,setCasesPage]=useState(0);const [search,setSearch]=useState('')
 const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [editingCase,setEditingCase]=useState(null);const [editingBank,setEditingBank]=useState(null); const [importRows,setImportRows]=useState(null)
 const demo=!configured && import.meta.env.DEV;const canEdit=demo?true: ['admin','editor'].includes(profile?.role)
 const isAuthorized=demo || Boolean(session && profile && ['admin','editor','viewer'].includes(profile.role))
 useEffect(()=>{if(!supabase)return;let live=true;supabase.auth.getSession().then(({data})=>{if(live){setSession(data.session);setAuthLoading(false)}}).catch(()=>setAuthLoading(false));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,s)=>setSession(s));return ()=>{live=false;subscription.unsubscribe()}},[])
 useEffect(()=>{if(!supabase){return};if(!session){setProfile(null);return};let cancelled=false;supabase.from('profiles').select('id,nama,role').eq('id',session.user.id).maybeSingle().then(({data,error})=>{if(!cancelled){setProfile(error?null:data);setLoginError(error?notify(error):(!data?'Akun belum mendapatkan hak akses. Minta administrator membuat profil dan role.':''))}});return ()=>{cancelled=true}},[session?.user?.id])
 const fetchAll=useCallback(async()=>{
   if(!supabase||!isAuthorized)return
   setLoading(true);setError('')
   try{
     const [m,a,b,total,open]=await Promise.all([
      supabase.from('bottlenecks').select('*').is('deleted_at',null).order('no'),
      supabase.from('action_plans').select('*').order('no'),
      supabase.from('bank_recap').select('*').order('bank'),
      supabase.from('sdm_cases').select('id',{head:true,count:'exact'}),
      supabase.from('sdm_cases').select('id',{head:true,count:'exact'}).gt('sisa_kewajiban',0)
     ])
     for(const q of [m,a,b,total,open])if(q.error)throw q.error
     setMatrix(m.data||[]);setActions(a.data||[]);setBankData(b.data||[]);setCaseTotal(total.count||0);setOpenTotal(open.count||0)
   }catch(err){setError(notify(err))}finally{setLoading(false)}
 },[isAuthorized])
 const fetchCases=useCallback(async()=>{
   if(!supabase||!isAuthorized)return
   const offset=casesPage*25
   let q=supabase.from('sdm_cases').select('*',{count:'exact'}).order('updated_at',{ascending:false}).range(offset,offset+24)
   const term=search.trim().replace(/[,%()]/g,'').slice(0,60)
   if(term)q=q.or(`nip.ilike.%${term}%,nama.ilike.%${term}%,provinsi.ilike.%${term}%`)
   const {data,error,count}=await q
   if(error)setError(notify(error)); else {setCases(data||[]);setCaseSearchTotal(count||0)}
 },[casesPage,search,isAuthorized])
 useEffect(()=>{if(isAuthorized&&!demo)fetchAll()},[isAuthorized,fetchAll,demo])
 useEffect(()=>{if(isAuthorized&&!demo&&page==='kasus')fetchCases()},[isAuthorized,fetchCases,demo,page])
 const signIn=async(email,password)=>{setBusy(true);setLoginError(''); const {error}=await supabase.auth.signInWithPassword({email,password}); if(error)setLoginError(notify(error));setBusy(false)}
 const signOut=async()=>{await supabase.auth.signOut();setPage('dashboard')}
 const updateData=async(table,no,patch)=>{
   if(!canEdit)return;setError('');if(demo){const setter=table==='bottlenecks'?setMatrix:setActions;setter(old=>old.map(r=>r.no===no?{...r,...patch}:r));return}
   const {error}=await supabase.from(table).update(patch).eq('no',no);if(error)setError(notify(error));else fetchAll()
 }
 const saveMatrix=async(record)=>{
  if(!canEdit||busy)return
  if(!record.kategori?.trim())return setMatrixError('Kategori wajib diisi.')
  const payload={};for(const k of ['kategori','risiko','tindak_lanjut','jalur','pic','koordinasi','prioritas','output','status','keputusan'])payload[k]=String(record[k]||'').trim()
  payload.deadline=record.deadline||null;setBusy(true);setMatrixError('')
  try{
   if(demo){setMatrix(old=>record.no?old.map(x=>x.no===record.no?{...x,...payload}:x):[...old,{...payload,no:Math.max(0,...old.map(x=>x.no))+1}])}
   else{const q=record.no?supabase.from('bottlenecks').update(payload).eq('no',record.no).is('deleted_at',null):supabase.from('bottlenecks').insert(payload);const {data,error}=await q.select('no').single();if(error)throw error;if(!data)throw new Error('Baris tidak tersedia. Muat ulang matriks.');await fetchAll()}
   setEditingMatrix(null)
  }catch(e){setMatrixError(notify(e))}finally{setBusy(false)}
 }
 const removeMatrix=async()=>{
  if(!canEdit||busy||!deletingMatrix)return;setBusy(true);setMatrixError('')
  try{if(demo)setMatrix(old=>old.filter(x=>x.no!==deletingMatrix.no));else{const {error}=await supabase.from('bottlenecks').update({deleted_at:new Date().toISOString()}).eq('no',deletingMatrix.no).is('deleted_at',null).select('no').single();if(error)throw error;await fetchAll()}setDeletingMatrix(null)}catch(e){setMatrixError(notify(e))}finally{setBusy(false)}
 }
 const saveCase=async(record)=>{
   const nip=String(record.nip||'').trim()
   if(!/^\d{18}$/.test(nip))return setError('NIP harus 18 digit angka sebagai teks. Jangan gunakan notasi ilmiah.')
   const obligation=Number(record.kewajiban_total||0), realization=Number(record.realisasi_total||0)
   if(!Number.isFinite(obligation)||!Number.isFinite(realization)||obligation<0||realization<0||realization>obligation)return setError('Nominal tidak valid: realisasi tidak boleh lebih besar dari kewajiban.')
   if(!record.nama?.trim())return setError('Nama wajib diisi.')
   setBusy(true);setError('')
   if(demo){setCases(old=>[{...record,id:Date.now(),sisa_kewajiban:obligation-realization},...old.filter(x=>x.nip!==nip)]);setCaseTotal(x=>x+(!cases.some(x=>x.nip===nip)?1:0));setEditingCase(null);setBusy(false);return}
   const payload={...record,nip,kewajiban_total:obligation,realisasi_total:realization,deadline:record.deadline||null,tanggal_pembayaran:record.tanggal_pembayaran||null}
   delete payload.sisa_kewajiban;delete payload.id;delete payload.created_at;delete payload.updated_at
   const result=editingCase?.id? await supabase.from('sdm_cases').update(payload).eq('id',editingCase.id):await supabase.from('sdm_cases').insert(payload)
   setBusy(false);if(result.error)setError(notify(result.error));else{setEditingCase(null);await Promise.all([fetchAll(),fetchCases()])}
 }
 const saveBank=async(record)=>{
   setBusy(true);setError('');const values={bank:record.bank,jumlah_sdm:record.jumlah_sdm===''?null:Number(record.jumlah_sdm),kewajiban_total:record.kewajiban_total===''?null:Number(record.kewajiban_total),realisasi_netto:record.realisasi_netto===''?null:Number(record.realisasi_netto),gagal_terakhir:record.gagal_terakhir===''?null:Number(record.gagal_terakhir),cutoff:record.cutoff||null,status:record.status||'',bukti:record.bukti||'',catatan:record.catatan||''}
   if(values.kewajiban_total!==null&&values.realisasi_netto!==null&&values.realisasi_netto>values.kewajiban_total){setError('Realisasi bank tidak boleh lebih besar dari kewajiban.');setBusy(false);return}
   if(demo){setBankData(old=>old.map(x=>x.bank===values.bank?values:x));setEditingBank(null);setBusy(false);return}
   const {error}=await supabase.from('bank_recap').update(values).eq('bank',values.bank)
   if(error)setError(notify(error));else{setEditingBank(null);fetchAll()}setBusy(false)
 }
 const kpis=useMemo(()=>{const all=bankData.filter(x=>x.kewajiban_total!==null&&x.realisasi_netto!==null);const complete=all.length===3;const obligation=all.reduce((s,x)=>s+Number(x.kewajiban_total),0);const realized=all.reduce((s,x)=>s+Number(x.realisasi_netto),0);return{obligation,realized,remaining:Math.max(0,obligation-realized),pct:obligation?Math.min(100,realized/obligation*100):0,complete,count:all.length}},[bankData])
 const doneActions=actions.filter(x=>x.status==='Selesai').length
 const doneMatrix=matrix.filter(x=>x.status==='Selesai').length
 const go=(p)=>{setPage(p);setNavOpen(false);setError('')}
 const handleXlsx=async file=>{
   if(!file)return;setError('')
   try{
    if(!file.name.toLowerCase().endsWith('.xlsx'))throw Error('Gunakan file Excel .xlsx dari sheet Tracker_SDM.')
    const rows=await readXlsxFile(file,{sheet:'Tracker_SDM'})
    const start=rows.findIndex(row=>String(row?.[0]||'').trim()==='No'&&String(row?.[1]||'').includes('NIP'))
    if(start<0)throw Error('Kolom sheet Tracker_SDM tidak ditemukan. Gunakan template Excel sumber.')
    const parsed=[];const problems=[];const seen=new Set()
    for(let i=start+1;i<rows.length;i++){
     const r=rows[i];if(!r||!r[1]&&!r[2])continue
     const nip=String(r[1]||'').trim()
     if(!/^\d{18}$/.test(nip)){problems.push(`Baris ${i+1}: NIP harus 18 digit dan berformat teks`);continue}
     if(seen.has(nip)){problems.push(`Baris ${i+1}: NIP duplikat di file`);continue}
     seen.add(nip)
     const kw=Number(r[7]||0),real=Number(r[8]||0)
     if(!Number.isFinite(kw)||!Number.isFinite(real)||kw<0||real<0||real>kw){problems.push(`Baris ${i+1}: nominal tidak valid`);continue}
     parsed.push({nip,nama:String(r[2]||''),provinsi:String(r[3]||''),kab_kota:String(r[4]||''),bank:String(r[5]||'Mandiri'),kategori:String(r[6]||''),kewajiban_total:kw,realisasi_total:real,tahap_terakhir:String(r[10]||''),jalur_penyelesaian:String(r[11]||''),pic:String(r[12]||''),deadline:null,status:statusesCase.includes(String(r[14]||''))?String(r[14]):'Belum Ditindaklanjuti',bukti:String(r[15]||''),tanggal_pembayaran:null,catatan:''})
    }
    setImportRows({rows:parsed,problems:problems.slice(0,20),problemCount:problems.length})
   }catch(err){setError(notify(err))}
 }
 const runImport=async()=>{
  if(!importRows||!canEdit||demo)return
  setBusy(true);setError('')
  const entries=importRows.rows
  let saved=0
  for(let i=0;i<entries.length;i+=100){
   const {error}=await supabase.from('sdm_cases').upsert(entries.slice(i,i+100),{onConflict:'nip'})
   if(error){setError(`Impor terhenti setelah ${saved} dari ${entries.length} baris. Tidak atomik; periksa data sebelum mengulang. ${notify(error)}`);setBusy(false);return}
   saved+=Math.min(100,entries.length-i)
  }
  setImportRows(null);setBusy(false);await Promise.all([fetchAll(),fetchCases()]);window.alert(`${saved} baris berhasil diimpor/diperbarui. Periksa bukti dan nominal sebelum menyatakan lunas.`)
 }
 const csvExport=async()=>{
  if(demo){window.alert('Ekspor data SDM hanya tersedia setelah database dan login diaktifkan.');return}
  setBusy(true);const all=[];let offset=0;let hasMore=true
  while(hasMore){const {data,error}=await supabase.from('sdm_cases').select('*').order('id').range(offset,offset+999);if(error){setError(notify(error));break}all.push(...data);hasMore=data.length===1000;offset+=1000}
  setBusy(false);if(!all.length)return
  const cols=['nip','nama','provinsi','kab_kota','bank','kategori','kewajiban_total','realisasi_total','sisa_kewajiban','tahap_terakhir','jalur_penyelesaian','pic','deadline','status','bukti','tanggal_pembayaran','catatan']
  const rows=[cols,...all.map(r=>cols.map(k=>r[k]??''))]
  const content='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n')
  const obj=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const el=document.createElement('a');el.href=obj;el.download='tukinumrecovery-tracker-sdm-'+new Date().toISOString().slice(0,10)+'.csv';document.body.appendChild(el);el.click();el.remove();URL.revokeObjectURL(obj)
 }
 if(!configured && !demo)return <div className="loading-page"><ShieldCheck size={35}/><h2>Konfigurasi aplikasi belum lengkap</h2><p>Hubungi administrator. Koneksi Supabase harus dikonfigurasi di Vercel.</p></div>
 if(!demo && (authLoading || (session&&!profile&&!loginError)))return <div className="loading-page"><LoaderCircle className="spin"/><p>Memverifikasi akses...</p></div>
 if(!demo && (!session || !profile))return <Login onSignIn={signIn} busy={busy} loginError={session&&!profile?'Akun belum mendapatkan akses. Minta administrator menetapkan profil/role.':loginError}/>
 return <div className="shell">
   <aside className={'sidebar '+(navOpen?'is-open':'')}>
    <div className="brand"><div className="brand-symbol"><ShieldCheck size={23}/></div><div><b>TukinUM<span>recovery</span></b><small>DIT. PSNK • 2026</small></div><button className="mobile-close icon-btn" onClick={()=>setNavOpen(false)}><X size={20}/></button></div>
    <div className="nav-label">WORKSPACE</div><nav>{menus.map(m=><button key={m.id} className={'nav-item '+(page===m.id?'active':'')} onClick={()=>go(m.id)}><m.icon size={18}/><span>{m.name}</span>{m.id==='kasus'&&caseTotal>0&&<small>{fmtN(caseTotal)}</small>}</button>)}</nav>
    <div className="nav-foot"><div className="deadline-widget"><span><Clock3 size={16}/> TENGGAT PENYELESAIAN</span><strong>31 Desember 2026</strong><div className="progress-rail"><i style={{width:kpis.pct+'%'}}/></div><small>Target pelunasan semua kewajiban</small></div><div className="nav-identity"><div className="avatar">{demo?'D':(profile?.nama||'P')[0].toUpperCase()}</div><div><b>{demo?'Mode Pratinjau':profile?.nama||session?.user?.email}</b><small>{demo?'Data simulasi':profile?.role?.toUpperCase()}</small></div>{!demo&&<button className="icon-btn" onClick={signOut} title="Keluar"><LogOut size={16}/></button>}</div></div>
   </aside>
   <div className="workspace"><header className="topbar"><div className="top-left"><button className="icon-btn hamburger" onClick={()=>setNavOpen(true)}><Menu size={22}/></button><span className="crumb">Direktorat PSNK <ChevronRight size={14}/> <b>{menus.find(m=>m.id===page)?.name}</b></span></div><div className="top-right"><span className="online-chip"><span className="green-dot"/>{demo?'PRATINJAU':'DATABASE AKTIF'}</span><span className="user-chip"><div className="avatar small">{demo?'D':(profile?.nama||'P')[0].toUpperCase()}</div>{demo?'Pratinjau':profile?.nama||'Pengguna'}</span></div></header>
   <main className="main">
    {demo&&<div className="notice demo-notice"><Info size={17}/><span><b>Mode pratinjau.</b> Perubahan hanya ada selama halaman terbuka. Belum memakai database dan <b>jangan masukkan data SDM riil</b>. Ikuti README untuk mengaktifkan login, database, dan Vercel.</span></div>}
    {error&&<div className="notice red-notice"><AlertTriangle size={18}/><span>{error}</span><button className="icon-btn" onClick={()=>setError('')}><X size={15}/></button></div>}
    {page==='dashboard'&&<><div className="page-title"><div><span className="eyebrow">OVERVIEW • TA 2025</span><h1>Pusat Kendali Pengembalian</h1><p>Monitoring kewajiban Tukin dan Uang Makan PPPK. Pastikan setiap nominal memiliki bukti penerimaan yang sah.</p></div><button className="btn secondary" disabled={demo||loading} onClick={fetchAll}><RefreshCw size={16}/> Perbarui data</button></div>
      <div className="stats-grid"><IconCard title="Total kewajiban" value={kpis.count?fmtRp(kpis.obligation):'Belum diisi'} subtitle="Dari rekap bank terverifikasi" icon={Landmark}/><IconCard title="Realisasi netto" value={kpis.count?fmtRp(kpis.realized):'Belum diisi'} subtitle="Penerimaan yang sudah direkonsiliasi" icon={CheckCircle2} accent="green"/><IconCard title="Sisa kewajiban" value={kpis.count?fmtRp(kpis.remaining):'Belum diisi'} subtitle="Kewajiban dikurangi realisasi" icon={TrendingUp} accent="amber"/><IconCard title="Kasus belum lunas" value={demo?'—':fmtN(openTotal)} subtitle="Tracker SDM khusus (bukan semua SDM)" icon={Users} accent="red"/></div>
      {!kpis.complete&&<div className="notice amber-notice"><Info size={18}/><span>Dashboard nominal belum lengkap: {3-kpis.count} bank belum memiliki angka kewajiban dan realisasi netto. Capaian gabungan belum dapat dinyatakan final.</span></div>}
      <div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">KINERJA PEMBAYARAN</span><h2>Capaian Pelunasan</h2></div><Pill value={kpis.complete?'Rekap 3 bank lengkap':'Menunggu rekonsiliasi'}/></div><div className="ratio"><strong>{kpis.count?kpis.pct.toFixed(1):'0,0'}<span>%</span></strong><span>Dari nominal bank terinput</span></div><div className="big-progress"><div style={{width:kpis.pct+'%'}}/></div><div className="ratio-foot"><span>Realisasi: {fmtRp(kpis.realized)}</span><span>Target 100%</span></div><div className="separator"/><h3>Rekap per bank</h3>{bankData.map(b=><div className="bank-mini" key={b.bank}><div><b>{b.bank}</b><small>{b.kewajiban_total==null?'Belum diinput':fmtRp(Number(b.kewajiban_total)-Number(b.realisasi_netto||0))+' sisa'}</small></div><div className="mini-track"><i style={{width:b.kewajiban_total? Math.min(100,100*Number(b.realisasi_netto||0)/Number(b.kewajiban_total))+'%':'0%'}}/></div></div>)}</section>
      <section className="panel"><div className="panel-heading"><div><span className="eyebrow">EKSEKUSI LAPANGAN</span><h2>Progres Rencana Aksi</h2></div><button className="text-button" onClick={()=>go('aksi')}>Lihat semua →</button></div><div className="plan-kpi"><strong>{doneActions}<span> / {actions.length}</span></strong><span>kegiatan selesai</span></div><div className="bar-stacked"><div style={{width:(doneActions/(actions.length||1)*100)+'%'}}/></div><div className="action-preview">{actions.filter(x=>x.status!=='Selesai').slice(0,4).map(a=><div key={a.no} className="action-peek"><span className="dot amber-dot"/><div><b>{a.kegiatan}</b><small>{safeDate(a.deadline)} · {a.pic}</small></div><Pill value={a.status}/></div>)}</div></section></div>
      <div className="two-callouts"><div className="callout dark"><span><HeartHandshake size={22}/> TINDAK LANJUT KHUSUS</span><h3>Jangan biarkan kasus nonaktif tertunda.</h3><p>SDM meninggal dunia, resign dan pensiun memerlukan verifikasi status, surat/tagihan sesuai ketentuan, serta telaah hukum-keuangan.</p><button className="btn light" onClick={()=>go('bottleneck')}>Buka Matriks <ChevronRight size={16}/></button></div><div className="callout soft"><span><CalendarDays size={22}/> KALENDER TARGET</span><h3>15 Desember: target operasional lunas</h3><p>16–31 Desember difokuskan untuk verifikasi bukti, rekonsiliasi dan keputusan pengecualian; kasus belum dibayar tetap berstatus belum lunas.</p><button className="btn secondary" onClick={()=>go('aksi')}>Lihat timeline <ChevronRight size={16}/></button></div></div>
     </>}
    {page==='bottleneck'&&<><div className="page-title"><div><span className="eyebrow">PENANGANAN HAMBATAN</span><h1>Matriks Bottleneck</h1><p>Kelola kategori permasalahan, tindak lanjut, PIC, target, bukti dan keputusan.</p></div><div><span className="count-pill">{doneMatrix}/{matrix.length} selesai</span> {canEdit&&<button className="btn primary" onClick={()=>{setMatrixError('');setEditingMatrix({status:'Belum Mulai',prioritas:'Tinggi'})}}><Plus size={16}/> Tambah Bottleneck</button>}</div></div><section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Kategori & Risiko</th><th>Tindak Lanjut / Jalur</th><th>PIC / Deadline</th><th>Prioritas</th><th>Status</th>{canEdit&&<th>Aksi</th>}</tr></thead><tbody>{matrix.map(m=><tr key={m.no}><td className="cat-col"><b>{String(m.no).padStart(2,'0')}. {m.kategori}</b><small>{m.risiko}</small></td><td className="long-col"><b>{m.tindak_lanjut}</b><small><b>Jalur:</b> {m.jalur}</small><small><b>Output:</b> {m.output}</small></td><td><b>{m.pic}</b><small>{safeDate(m.deadline)}</small></td><td><Pill value={m.prioritas}/></td><td>{canEdit?<select className="status-select" value={m.status||'Belum Mulai'} onChange={e=>updateData('bottlenecks',m.no,{status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select>:<Pill value={m.status}/>}</td>{canEdit&&<td><button className="btn secondary" onClick={()=>{setMatrixError('');setEditingMatrix(m)}}><Pencil size={14}/> Edit</button> <button className="btn secondary" onClick={()=>{setMatrixError('');setDeletingMatrix(m)}}>Hapus</button></td>}</tr>)}</tbody></table></div></section></>}
    {page==='aksi'&&<><div className="page-title"><div><span className="eyebrow">RENCANA TINDAK LANJUT</span><h1>Roadmap Oktober–Desember</h1><p>Monitoring pelaksanaan, PIC, tanggal target, dan tingkat progres setiap kegiatan.</p></div><div className="progress-counter"><strong>{Math.round(doneActions/(actions.length||1)*100)}%</strong><span>kegiatan selesai</span></div></div><div className="action-list">{actions.map(a=><section key={a.no} className="plan-row"><div className="plan-number">{String(a.no).padStart(2,'0')}</div><div className="plan-body"><div className="plan-title"><h3>{a.kegiatan}</h3><Pill value={a.prioritas}/></div><p>{a.langkah}</p><div className="plan-meta"><span><Users size={14}/> {a.pic}</span><span><CalendarDays size={14}/> {safeDate(a.mulai)} – {safeDate(a.deadline)}</span><span><FileCheck2 size={14}/> {a.output}</span></div><div className="plan-progress"><div style={{width:Number(a.progres||0)+'%'}}/></div></div><div className="plan-edit"><small>{Number(a.progres||0)}% progres</small>{canEdit?<><select className="status-select" value={a.status||'Belum Mulai'} onChange={e=>updateData('action_plans',a.no,{status:e.target.value,progres:e.target.value==='Selesai'?100:Number(a.progres||0)})}>{statuses.map(s=><option key={s}>{s}</option>)}</select><input type="range" min="0" max="100" step="10" value={Number(a.progres||0)} aria-label={'Progres '+a.kegiatan} onChange={e=>updateData('action_plans',a.no,{progres:Number(e.target.value)})}/></>:<Pill value={a.status}/>}</div></section>)}</div></>}
    {page==='bank'&&<><div className="page-title"><div><span className="eyebrow">REKONSILIASI PERBANKAN</span><h1>Rekap Mandiri, BRI & BSI</h1><p>Isikan hanya angka yang telah direkonsiliasi. Pengamatan historis tidak boleh dijumlahkan ulang.</p></div></div><div className="bank-grid">{bankData.map(b=><div className="bank-card" key={b.bank}><div className="bank-card-top"><div className="bank-icon"><Landmark size={20}/></div><div><span className="eyebrow">MITRA PEMBAYARAN</span><h2>Bank {b.bank}</h2></div>{canEdit&&<button className="icon-btn edit-card" onClick={()=>setEditingBank({...b})} title="Edit rekap"><Pencil size={17}/></button>}</div><div className="bank-value"><span>Sisa kewajiban</span><strong>{b.kewajiban_total!=null&&b.realisasi_netto!=null?fmtRp(Number(b.kewajiban_total)-Number(b.realisasi_netto)):'Belum diisi'}</strong></div><div className="bank-metrics"><div><span>Kewajiban</span><b>{b.kewajiban_total!=null?fmtRp(b.kewajiban_total):'—'}</b></div><div><span>Realisasi</span><b>{b.realisasi_netto!=null?fmtRp(b.realisasi_netto):'—'}</b></div><div><span>Debit gagal terakhir</span><b>{b.gagal_terakhir==null?'Belum diisi':fmtN(b.gagal_terakhir)+' SDM'}</b></div><div><span>Cut-off</span><b>{safeDate(b.cutoff)}</b></div></div><div className="bank-card-footer"><Pill value={b.status||'Menunggu rekonsiliasi'}/><span>{b.bukti?'Bukti: '+b.bukti:'Bukti belum dilampirkan'}</span></div></div>)}</div><div className="notice amber-notice"><Info size={18}/><span>Angka 5.125 berhasil / 594 gagal Mandiri dan 166 gagal BRI merupakan observasi historis yang harus diverifikasi ulang; angka tersebut sengaja tidak dijadikan realisasi nominal otomatis.</span></div></>}
    {page==='kasus'&&<><div className="page-title"><div><span className="eyebrow">BNBA / KASUS KHUSUS</span><h1>Monitoring Pengembalian per SDM</h1><p>Satu NIP satu kewajiban konsolidasi. Status lunas wajib didukung bukti penerimaan resmi.</p></div><div className="toolbar">{canEdit&&<><label className="btn secondary file-btn"><Upload size={16}/> Impor Excel<input type="file" hidden accept=".xlsx" onChange={e=>{handleXlsx(e.target.files?.[0]);e.target.value=''}}/></label><button className="btn primary" onClick={()=>setEditingCase({...initCase})}><Plus size={17}/> Tambah SDM</button></>}<button className="btn secondary" onClick={csvExport} disabled={busy||demo}><Download size={16}/> Ekspor CSV</button></div></div><section className="panel table-panel"><div className="panel-filter"><label className="search-box"><Search size={17}/><input placeholder="Cari NIP, nama, provinsi..." value={search} onChange={e=>{setSearch(e.target.value);setCasesPage(0)}}/></label><span className="results">{fmtN(search?caseSearchTotal:caseTotal)} data {search?'hasil pencarian':'tercatat'}</span></div><div className="table-scroll"><table><thead><tr><th>SDM / Wilayah</th><th>Kategori</th><th>Kewajiban / Realisasi</th><th>Sisa</th><th>Deadline</th><th>Status</th><th></th></tr></thead><tbody>{!cases.length?<tr><td colSpan="7" className="empty"><Users size={32}/><b>Belum ada data SDM</b><span>{demo?'Aplikasi pratinjau tidak memuat data personel riil.':'Tambah data atau impor dari spreadsheet Tracker_SDM.'}</span></td></tr>:cases.map(c=><tr key={c.id||c.nip}><td><b>{c.nama}</b><small className="mono">{c.nip}</small><small>{[c.provinsi,c.kab_kota].filter(Boolean).join(' / ')} · {c.bank}</small></td><td><Pill value={c.kategori}/></td><td><b>{fmtRp(c.kewajiban_total)}</b><small>Realisasi {fmtRp(c.realisasi_total)}</small></td><td><b className="danger-text">{fmtRp(c.sisa_kewajiban)}</b></td><td>{safeDate(c.deadline)}</td><td><Pill value={c.status}/></td><td>{canEdit&&<button className="icon-btn" onClick={()=>setEditingCase(c)} title="Edit SDM"><Pencil size={17}/></button>}</td></tr>)}</tbody></table></div><div className="pagination"><span>Halaman {casesPage+1} · 25 baris per halaman</span><div><button className="icon-btn" disabled={casesPage===0} onClick={()=>setCasesPage(x=>x-1)}><ChevronLeft size={20}/></button><button className="icon-btn" disabled={(casesPage+1)*25>=(search?caseSearchTotal:caseTotal)} onClick={()=>setCasesPage(x=>x+1)}><ChevronRight size={20}/></button></div></div></section></>}
    {page==='panduan'&&<><div className="page-title"><div><span className="eyebrow">PENGGUNAAN APLIKASI</span><h1>Panduan & Tata Kelola</h1><p>Prinsip pengendalian agar progres dapat dipertanggungjawabkan saat penutupan tahun.</p></div></div><div className="guide-grid"><section className="panel guide"><h2>Alur kerja</h2><ol><li>Input dan rekonsiliasi kewajiban per bank; jangan memakai estimasi.</li><li>Identifikasi SDM tertunggak pada Monitoring SDM (NIP sebagai 18 digit teks).</li><li>Tetapkan kategori hambatan dan PIC tindak lanjut.</li><li>Perbarui hasil penagihan, bukti setor, dan status setelah divalidasi.</li><li>Pantau 15 rencana aksi sampai target operasional 15 Desember.</li><li>Tutup seluruh transaksi terverifikasi pada 31 Desember 2026.</li></ol></section><section className="panel guide"><h2>Pengendalian penting</h2><ul><li>Pengembalian via bank dan setoran langsung wajib direkonsiliasi agar tidak ganda.</li><li>SDM meninggal dunia dan status nonaktif memerlukan mekanisme resmi dari bagian keuangan/hukum.</li><li>Kasus dalam proses telaah tetap dicatat <b>belum lunas</b> sampai bukti pembayaran sah tersedia.</li><li>Hak akses <b>admin / editor / viewer</b> harus disetujui administrator.</li><li>Gunakan impor Excel pada <b>Tracker_SDM</b>; rekap bank dimasukkan terpisah.</li></ul></section><section className="panel guide"><h2>Privasi</h2><p>Data NIP dan kewajiban adalah data internal. Jangan membuka pendaftaran publik, gunakan RLS di Supabase, dan batasi domain atau akun yang memiliki izin akses.</p><p><b>Prototipe:</b> fitur dasar belum mencakup persetujuan bertingkat, audit log tindakan terperinci, verifikasi NTPN otomatis, atau mekanisme import transaksi atomik. Uji sebelum data produksi digunakan.</p></section></div></>}
   </main><footer className="footer">TukinUMrecovery • Dit. PSNK • Internal use only <span>TA 2025 → Penyelesaian 2026</span></footer></div>
   {navOpen&&<div className="mobile-overlay" onClick={()=>setNavOpen(false)}/>}
   {editingMatrix&&<BottleneckModal value={editingMatrix} busy={busy} error={matrixError} onSave={saveMatrix} onClose={()=>{if(!busy)setEditingMatrix(null)}}/>}
   {deletingMatrix&&<Modal title="Hapus Bottleneck" onClose={()=>{if(!busy)setDeletingMatrix(null)}} footer={<><button className="btn secondary" disabled={busy} onClick={()=>setDeletingMatrix(null)}>Batal</button><button className="btn primary" disabled={busy} onClick={removeMatrix}>Ya, hapus</button></>}><p>Hapus kategori <b>{deletingMatrix.kategori}</b> dari matriks? Data kasus SDM tidak ikut dihapus.</p>{matrixError&&<p role="alert" className="notice red-notice">{matrixError}</p>}</Modal>}
   {editingCase&&<CaseModal value={editingCase} onClose={()=>setEditingCase(null)} onSave={saveCase} busy={busy} categories={[...new Set([...matrix.map(x=>x.kategori),...cases.map(x=>x.kategori)].filter(Boolean))]}/>}
   {editingBank&&<BankModal value={editingBank} onClose={()=>setEditingBank(null)} onSave={saveBank} busy={busy}/>}
   {importRows&&<Modal title="Pratinjau impor Excel" onClose={()=>setImportRows(null)} footer={<><button className="btn secondary" onClick={()=>setImportRows(null)}>Batal</button><button className="btn primary" disabled={demo||busy||importRows.problemCount>0||!importRows.rows.length} onClick={runImport}>{busy?<LoaderCircle className="spin" size={16}/>:<Upload size={16}/>} Konfirmasi impor</button></>}><p><b>{fmtN(importRows.rows.length)} baris valid</b> · {fmtN(importRows.problemCount)} baris bermasalah.</p><div className="notice amber-notice"><Info size={16}/><span>Impor memperbarui baris dengan NIP yang sama. Pastikan nominal final disetujui. Proses batch bukan transaksi tunggal; dapat terhenti sebagian bila koneksi gagal.</span></div>{importRows.problems.length>0&&<div className="error-list">{importRows.problems.map((v,i)=><p key={i}>{v}</p>)}</div>}{demo&&<div className="notice red-notice">Impor dinonaktifkan di mode pratinjau untuk melindungi data SDM.</div>}</Modal>}
 </div>
}
function Field({label,field,value,onChange,children,type='text',required=false,readonly=false,placeholder=''}){return <label className="form-field"><span>{label}</span>{children||<input type={type} value={value??''} onChange={e=>onChange(field,e.target.value)} required={required} readOnly={readonly} placeholder={placeholder}/>}</label>}
function CaseModal({value,onClose,onSave,busy,categories=kategoriList}){const[r,setR]=useState({...value});const up=(k,v)=>setR(x=>({...x,[k]:v}));const amount=Number(r.kewajiban_total||0)-Number(r.realisasi_total||0);return <Modal title={value.id?'Perbarui Kasus SDM':'Tambah Kasus SDM'} onClose={onClose} footer={<><button className="btn secondary" onClick={onClose}>Batal</button><button className="btn primary" onClick={()=>onSave(r)} disabled={busy}>{busy?<LoaderCircle size={16} className="spin"/>:<CheckCircle2 size={16}/>} Simpan data</button></>}><div className="form-grid"><Field label="NIP (18 digit)" field="nip" value={r.nip} onChange={up} readonly={!!value.id}/><Field label="Nama SDM" field="nama" value={r.nama} onChange={up}/><Field label="Provinsi" field="provinsi" value={r.provinsi} onChange={up}/><Field label="Kabupaten / Kota" field="kab_kota" value={r.kab_kota} onChange={up}/><Field label="Bank" field="bank" value={r.bank} onChange={up}><select value={r.bank||'Mandiri'} onChange={e=>up('bank',e.target.value)}>{banks.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Kategori Bottleneck" field="kategori" value={r.kategori} onChange={up}><select value={r.kategori||''} onChange={e=>up('kategori',e.target.value)}><option value="">Pilih kategori</option>{[...new Set([...categories,r.kategori].filter(Boolean))].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Kewajiban Final (Rp)" field="kewajiban_total" type="number" value={r.kewajiban_total} onChange={up}/><Field label="Realisasi Netto (Rp)" field="realisasi_total" type="number" value={r.realisasi_total} onChange={up}/><div className="balance-field"><span>Sisa kewajiban (otomatis)</span><strong>{fmtRp(amount)}</strong></div><Field label="Tahap Terakhir" field="tahap_terakhir" value={r.tahap_terakhir} onChange={up}/><Field label="Jalur Penyelesaian" field="jalur_penyelesaian" value={r.jalur_penyelesaian} onChange={up}/><Field label="PIC" field="pic" value={r.pic} onChange={up}/><Field label="Deadline" type="date" field="deadline" value={r.deadline} onChange={up}/><Field label="Status" field="status" value={r.status} onChange={up}><select value={r.status||'Belum Ditindaklanjuti'} onChange={e=>up('status',e.target.value)}>{statusesCase.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Bukti / NTPN / Nomor Surat" field="bukti" value={r.bukti} onChange={up}/><Field label="Tanggal Pembayaran" field="tanggal_pembayaran" value={r.tanggal_pembayaran} type="date" onChange={up}/><label className="form-field full"><span>Catatan Tindak Lanjut</span><textarea value={r.catatan||''} onChange={e=>up('catatan',e.target.value)} rows="3" placeholder="Hasil koordinasi, langkah terakhir, keputusan..."/></label></div></Modal>}
function BottleneckModal({value,onClose,onSave,busy,error}){const[r,setR]=useState({...value});const up=(k,v)=>setR(x=>({...x,[k]:v}));return <Modal title={value.no?'Edit Bottleneck':'Tambah Bottleneck'} onClose={onClose} footer={<><button className="btn secondary" disabled={busy} onClick={onClose}>Batal</button><button className="btn primary" disabled={busy} onClick={()=>onSave(r)}>{busy?'Menyimpan...':'Simpan'}</button></>}><div className="form-grid">{[['kategori','Kategori'],['risiko','Risiko'],['tindak_lanjut','Tindak Lanjut'],['jalur','Jalur Penyelesaian'],['pic','PIC'],['koordinasi','Koordinasi'],['output','Output / Bukti'],['keputusan','Keputusan']].map(([k,label])=><Field key={k} label={label} field={k} value={r[k]} onChange={up}/>)}<Field label="Deadline" field="deadline" type="date" value={r.deadline} onChange={up}/><Field label="Prioritas"><select value={r.prioritas||'Tinggi'} onChange={e=>up('prioritas',e.target.value)}>{[...new Set(['Kritis','Tinggi','Sedang','Rendah',r.prioritas].filter(Boolean))].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Status"><select value={r.status||'Belum Mulai'} onChange={e=>up('status',e.target.value)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></Field></div>{error&&<p role="alert" className="notice red-notice">{error}</p>}</Modal>}
function BankModal({value,onClose,onSave,busy}){const[r,setR]=useState({...value});const up=(k,v)=>setR(x=>({...x,[k]:v}));return <Modal title={'Rekonsiliasi Bank '+r.bank} onClose={onClose} footer={<><button className="btn secondary" onClick={onClose}>Batal</button><button className="btn primary" onClick={()=>onSave(r)} disabled={busy}><CheckCircle2 size={16}/> Simpan rekap</button></>}><div className="form-grid"><Field label="Jumlah SDM Wajib" field="jumlah_sdm" type="number" value={r.jumlah_sdm} onChange={up}/><Field label="Debit gagal terakhir (SDM)" field="gagal_terakhir" type="number" value={r.gagal_terakhir} onChange={up}/><Field label="Total kewajiban (Rp)" field="kewajiban_total" type="number" value={r.kewajiban_total} onChange={up}/><Field label="Realisasi netto (Rp)" field="realisasi_netto" type="number" value={r.realisasi_netto} onChange={up}/><Field label="Tanggal cut-off" field="cutoff" type="date" value={r.cutoff} onChange={up}/><Field label="Status eksekusi" field="status" value={r.status} onChange={up}/><Field label="Referensi bukti" field="bukti" value={r.bukti} onChange={up}/><Field label="Catatan" field="catatan" value={r.catatan} onChange={up}/></div><div className="notice amber-notice"><Info size={16}/> Jangan memasukkan angka yang belum direkonsiliasi atau menggabungkan dua tahap hasil debit tanpa pengecekan ulang.</div></Modal>}

createRoot(document.getElementById('root')).render(<App />)
